export type TLevelThreeAcTree = {
  l2_code: string;
  l3_code?: string;
  l3_description: string;
};

export type TLevelFourAcTree = {
  l3_code: string;
  l4_code?: string;
  l4_description: string;
  l4_type: string;
  l4_bill: string;
  l4_job: string;
};
export type TAccountChildren = {
  ac_code?: string;
  ac_name: string;
  country_code: string;
  territory_code: string;
  address_1: string;
  address_2: string;
  address_3: string;
  phone: string;
  fax: string;
  e_mail: string;
  contact_person: string;
  mobile_no: string;
  exp_alloc?: string;
  l4_code: string;
  curr_code: string;
  ac_type?: string;
  ac_active?: string;
  credit_period: number;
  credit_amount: number;
  exp_type_code?: string;
  pl_bl_code: string;
  ac_status?: string;
  dept_code: string;
  exp_subtype_code?: string;
  bank_ac_code: string;
  bank_name: string;
  bank_swift: string;
  salesman_code: string;
  sector_code: string;
  exp_type_code_back?: string;
  exp_subtype_code_back?: string;
  contract_expry_date: Date;
  bi_main_group: string;
  bi_sub_group: string;
  bi_exp_type: string;
  bi_pl_bs_ind: string;
  bi_dept: string;
  trn_no: string;
  ac_infze: string;
  tax_registrd: string;
  city_name: string;
  tax_country_code: string;
  rcm_apply: string;
  approved_by?: string;
  approved_date?: Date;
  cr_no?: string;
  apprval_factor?: string;
  request_number?: string;
  files: string[];
};
