export interface ICustomer{
  company_code: string;
  prin_code: string;
  cust_code?: string;
  curr_code?: string | null;
  country_code?: string | null;
  cust_name: string;
  cust_addr1?: string | null;
  cust_addr2?: string | null;
  cust_addr3?: string | null;
  cust_addr4?: string | null;
  cust_city?: string | null;
  cust_contact1?: string | null;
  cust_telno1?: string | null;
  cust_faxno1?: string | null;
  cust_email1?: string | null;
  cust_contact2?: string | null;
  cust_telno2?: string | null;
  cust_faxno2?: string | null;
  cust_email2?: string | null;
  cust_contact3?: string | null;
  cust_telno3?: string | null;
  cust_faxno3?: string | null;
  cust_ref1?: string | null;
  cust_ref2?: string | null;
  cust_ref3?: string | null;
  service_date?: Date | string | null;
  cust_acref?: string | null;
  cust_credit?: number | null;
  cust_stat?: string | null;
  cust_imp_code?: string | null;
  cust_lic_no?: string | null;
  cust_lic_type?: string | null;
  user_id?: string | null;
  date_time?: Date | string | null;
  price_check?: string | null;
  cust_email3?: string | null;
  payment_terms?: number | null;
  importer_code?: string | null;
  reff_cust_code?: string | null;
  min_exp_days?: number | null;
  cust_mobile_no?: string | null;
  vat_no?: string | null;
  cust_photo?: string | null;
  label_seq_no?: number | null;
  cust_prefix?: string | null;
  act_code?: string | null;
  zone_id?: string | null;
}
