version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install -g yarn
      - yarn
  build:
    commands:
      - echo Build started on $(date)
      - |
        export REACT_APP_VERSION=$REACT_APP_VERSION
        export REACT_APP_BASE_URL=$REACT_APP_BASE_URL
        export REACT_APP_API_URL=$REACT_APP_API_URL
        export GENERATE_SOURCEMAP=$GENERATE_SOURCEMAP
        NODE_OPTIONS=--max-old-space-size=12288
        yarn build
  post_build:
    commands:
      - if [[ -z "$BUCKET_NAME" || -z "$CLOUDFRONT_DISTRIBUTION_ID" ]]; then echo "Environment variables missing"; exit 1; fi
      - echo Uploading build artifacts to S3...
      - aws s3 sync --acl public-read ./build s3://$BUCKET_NAME/
      - echo "Checking for build artifacts..."
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html s3://$BUCKET_NAME/
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths '/*'
artifacts:
  files:
    - 'build/**/*'
