import Joi from "joi";
import { IJobInboundWms } from "../../../interfaces/wms/transaction/inbound/inboundJobWms.interface";

export const createInboundSchema = (
  data: IJobInboundWms,
  isBulkOperation: boolean,
  companyCode: string
) => {
  const createinboundjobSchema = Joi.object().keys({
    company_code: Joi.string().valid(companyCode).required(),
    prin_code: Joi.any().required(),
    job_type: Joi.string().required(),
    job_date: Joi.date(),
    job_no: Joi.string().allow(""),
    job_class: Joi.string().allow(""),
    dept_code: Joi.string().allow(""),
    transport_mode: Joi.string().allow(""),
   doc_ref: Joi.string().allow("", null),
   port_code: Joi.string().allow("", null),
    description1: Joi.string().allow("", null),
    description2: Joi.string().allow("", null),
    prin_ref1: Joi.string().allow("", null),
    prin_ref2: Joi.string().allow("", null),
    remarks: Joi.string().allow("", null),
    eta: Joi.date().allow("", null),
    ata: Joi.date().allow("", null),
    etd: Joi.date().allow("", null),
    schedule_date: Joi.date().allow("", null),
    payment_terms: Joi.string().allow("", null),
    curr_code: Joi.string().allow("", null),
    ex_rate: Joi.number(),
    frieght_value: Joi.number().allow("", null),
    insurance_value: Joi.number().allow("", null),
    cust_code: Joi.string().allow("", null),
    container_flag: Joi.string().allow("", null),
    container: Joi.string().allow("", null),
    container_date: Joi.date().allow("", null),
    packdet: Joi.string().allow("", null),
    packdet_date: Joi.date().allow("", null),
    allocated: Joi.string().allow("", null),
    allocate_date: Joi.date().allow("", null),
    canceled: Joi.string().allow("", null),
    cancel_date: Joi.date().allow("", null),
    confirmed: Joi.string().allow("", null),
    confirm_date: Joi.date().allow("", null),
    grn_no: Joi.number().allow(null),
    grn_date: Joi.date().allow("", null),
    invoiced: Joi.string().allow("", null),
    invoice_date: Joi.date().allow("", null),
    completed: Joi.string().allow("", null),
    complete_date: Joi.date().allow("", null),
    // user_id: Joi.string().allow(""),
    // user_dt: Joi.date(),
    exp_jobno: Joi.string().allow("", null),
    picked: Joi.string().allow("", null),
    picked_date: Joi.date().allow("", null),
    order_date: Joi.date().allow("", null),
    ordered: Joi.string().allow("", null),
    destination_port: Joi.string().allow("", null),
    vessel_name: Joi.string().allow("", null),
    voyage_no: Joi.string().allow("", null),
    payableat: Joi.string().allow("", null),
    place_receipt: Joi.string().allow("", null),
    place_delivery: Joi.string().allow("", null),
    no_of_original_bl: Joi.number().allow(null),
    broker_code: Joi.string().allow("", null),
    quotation_ref: Joi.string().allow("", null),

    // be_no: Joi.string().allow(""),
    //be_date: Joi.date(),
    //be_dep_amount: Joi.number(),
    //deposit_collected: Joi.string().allow(""),
    //deposit_collected_dt: Joi.date(),
    //deposit_collected_no: Joi.number(),
    be_deposits: Joi.string().allow(""),
    ind_freight: Joi.string().allow(""),
    country_origin: Joi.string().allow(""),
    country_destination: Joi.string().allow(""),
    //task_order: Joi.number().allow(null),
    custom_recno: Joi.string().allow("", null),
    doc_ref2: Joi.string().allow("", null),
    hawb: Joi.string().allow("", null),
    reexport: Joi.string().allow("", null),
    ref_jobno: Joi.string().allow("", null),
    combined_jobno: Joi.string().allow("", null),
    carrier: Joi.string().allow("", null),
    job_lock: Joi.string().allow("", null),
    courier_code: Joi.string().allow("", null),
    delivery_point: Joi.string().allow("", null),
    // dep_batchdate: Joi.date(),
    //dep_batchentry: Joi.number(),
    div_code: Joi.string().allow(""),
    doc_deposit_expiry: Joi.date().allow("", null),
    salesman_code: Joi.string().allow("", null),
    transit_time: Joi.string().allow("", null),
    document_check: Joi.string().allow("", null),
    delivery_remarks: Joi.string().allow("", null),
    cargo_received: Joi.string().allow("", null),
    delivered_by: Joi.string().allow("", null),
    canceled_by: Joi.string().allow("", null),
    cancel_remarks: Joi.string().allow("", null),
    send_mail: Joi.string().allow("", null),
    backlog_mail: Joi.string().allow("", null),
    dplan_flag: Joi.string().allow("", null),
    trans_batch_id: Joi.string().allow("", null),
    send_mail_dn: Joi.string().allow("", null),
    kpi_inc: Joi.string().allow("", null),
    kpi_exc_remark: Joi.string().allow("", null),
    job_category: Joi.string().allow("", null),
    edit_user: Joi.string().allow("", null),
    tx_cat_code: Joi.string().allow("", null),
    bcf_code: Joi.string().allow("", null),
    dn_print_date: Joi.date(),
    test_code: Joi.string().allow("", null),
    dec_no: Joi.string().allow("", null),
    port_exit: Joi.string().allow("", null),
    request_category: Joi.string().allow("", null),
    load_point: Joi.string().allow("", null),
    created_at: Joi.date().allow(null),
    created_by: Joi.string(),
    updated_at: Joi.date().allow(null),
    updated_by: Joi.string(),
  });
  return createinboundjobSchema.validate(data);
};
