import { TAccountChildren } from 'pages/Finance/types/acTree.types';
import { TJobInboundWms, TTransactionExpenseDetail, TTransactionJobDetail } from 'pages/WMS/Transaction/Inbound/types/jobInbound_wms.types';
import { TCurrency } from 'pages/WMS/types/currency-wms.types';
import { TDivision } from 'pages/WMS/types/employee-hr.types';
import { TBankTransaction } from 'types/columns.types';
import { TFile } from 'types/types.file';

export type TDetailRowSelection = {
  [key: string]: {
    ac_code: string;
    table: { name: 'invoice' | 'job' | 'expense' | ''; code: string };
    div_code?: string;
    doc_type?: string;
    doc_no?: number;
    serial_no?: number;
  };
};
export type TTransactionDocumentView = {
  company_code: string;
  doc_type: string;
  doc_no: number;
  doc_date: Date;
  ac_name: string;
  remarks: string;
  ref_no: string;
  create_user: string;
  cheque_no: string;
  cheque_date: Date;
  ac_payee: string;
  ref_doc_no: string;
  remittance: string;
  amount: number;
  canceled: string;
  div_code: string;
  fy_period: string;
  cheque_bank: string;
  user_id: string;
  create_dt: Date;
};
export type TTransactionDocumentHeader = {
  doc_type: string;
  doc_no: number;
  doc_date: string;
  ac_code: string;
  bank_ac_code?: string;
  ref_no?: string;
  ref_date?: Date;
  remarks: string;
  curr_code: string;
  curr_name?: string;
  ex_rate: number;
  cheque_no?: string;
  cheque_date?: string;
  ac_payee?: string;
  div_code: string;
  company_code?: string;
  canceled?: string;
  create_user?: string;
  create_date?: Date;
  last_serial_no?: number;
  last_dtl_serial_no?: number;
  payment_terms?: string;
  lpo_no?: string;
  lpo_date?: Date;
  credit_period?: number;
  due_date?: Date;
  ref_doc_type?: string;
  cheque_bank?: string;
  party_name?: string;
  party_address?: string;
  party_phone?: string;
  party_fax?: string;
  remittance?: string;
  auto_reverse?: string;
  salesman_code?: string;
  sector_code?: string;
  sys_gen?: string;
  tx_cat_code?: string;
  tx_compntcat_code_1?: string;
  tx_compntcat_code_2?: string;
  tx_compntcat_code_3?: string;
  tx_compntcat_code_4?: string;
  tx_compnt_1_expmt?: string;
  tx_tax_filed?: string;
  tx_tax_filed_dt?: Date;
  tx_tax_filed_refno?: string;
  tx_compnt_hdisc_amt_1?: number;
  doc_path?: string;
  ref_doc_no?: string;
  vat_trn_no?: string;
  updated_at?: Date;
  updated_by?: string;
  created_by?: string;
  created_at?: Date;
  files?: TFile[];
};

export type TTransactionDetails = {
  Department?: { dept_name: string };
  Currency?: { curr_name: string };

  company_code: string;
  doc_type: string;
  doc_no: number;
  serial_no: number;
  doc_date: Date;
  ac_code: string;
  header_ac_code?: string;
  bank_ac_code?: string;
  remarks: string;
  amount: number;
  sign_ind: number;
  curr_code: string;
  ex_rate: number;
  lcur_amount: number;
  pdc_ind?: string;
  cheque_no?: string;
  cheque_date?: Date;
  cheque_desc?: string;
  pdc_cleared_date?: Date;
  canceled?: string;
  job_no?: string;
  recon_ind?: string;
  recon_date?: Date;
  dept_code: string;
  qty?: number;
  price?: number;
  uom?: string;
  pdc_clear_jvno?: number;
  ref_doc_type?: string;
  ref_doc_no?: string;
  ref_doc_serial_no?: number;
  div_code: string;
  tx_cat_code: string;
  tx_compntcat_code_1: string;
  tx_compntcat_code_2?: string;
  tx_compntcat_code_3?: string;
  tx_compntcat_code_4?: string;
  tx_compnt_perc_1: number;
  tx_compnt_perc_2?: number;
  tx_compnt_perc_3?: number;
  tx_compnt_perc_4?: number;
  tx_compnt_amt_1: number;
  tx_compnt_amt_2?: number;
  tx_compnt_amt_3?: number;
  tx_compnt_amt_4?: number;
  tx_compnt_lcuramt_1: number;
  tx_compnt_lcuramt_2?: number;
  tx_compnt_lcuramt_3?: number;
  tx_compnt_lcuramt_4?: number;
  tx_compnt_1_expmt: string;
  tx_compnt_2_exmpt?: string;
  tx_compnt_3_exmpt?: string;
  tx_compnt_4_exmpt?: string;
  tx_tax_filed?: string;
  tx_tax_filed_dt?: Date;
  tx_tax_filed_refno?: string;
  tx_compnt_hdisc_amt_1?: number;
  updated_at?: Date;
  updated_by?: string;
  created_by?: string;
  created_at?: Date;
};
export type TTransactionChildren<T extends TDetailRowSelection[string]['table']['name']> = (T extends 'invoice'
  ? TTransactionInvoiceDetail
  : T extends 'job'
  ? TJobInboundWms
  : (TTransactionInvoiceDetail | TTransactionJobDetail | TTransactionExpenseDetail) & {
      IsDeletable?: boolean;
      curr_name?: string;
      c_curr_name_orgin?: string;
    }) & {
  isEditMode: boolean;
  id: string;
};

export type TTransactionInvoiceDetail = {
  company_code: string;
  doc_type: string;
  doc_no: number;
  serial_no: number;
  dtl_sr_no: number;
  doc_date: Date;
  ac_code: string;
  inv_no: string;
  inv_date: Date;
  due_date: Date;
  chq_no: string;
  chq_date: Date;
  chq_bank: string;
  amount: number;
  lcur_amount: number;
  sign_ind: number;
  curr_code: string;
  ex_rate: number;
  ex_rate_origin: number;
  curr_code_origin: string;
  amount_origin: number;
  indicator_origin: string;
  div_code: string;
  oracle_upload: string;
  oracle_dt: Date;
  created_by: string;
  created_at: Date;
  updated_by: string;
  updated_at: Date;
};
export type TFyPeriod = {
  company_code: string;
  fy_period: string;
  date_from: Date;
  date_to: Date;
  sort_order: number;
};
export type TBank = {
  ac_code: string;
  ac_name: string;
};
export type TTransactionDocumentReport = {
  company_name: string;
  hdr_ac_code: string;
  doc_no: number;
  doc_date: string; // ISO 8601 string format
  cheque_no: string | null;
  cheque_date: string | null;
  party_name: string | null;
  prepared: string;
  verified: string;
  approved: string;
  bank_name_inv: string;
  company_address1: string;
  company_address2: string;
  company_address3: string;
  products: TTransactionProduct[];
};

export type TTransactionProduct = {
  doc_type: string;
  doc_no: number;
  doc_date: string;
  hdr_ac_code: string;
  hdr_remarks: string;
  hdr_curr_code: string;
  hdr_ex_rate: string;
  cheque_no: string;
  isTotal: boolean;
  total: string;
  cheque_date: string;
  serial_no: number;
  dtl_ac_code: string;
  remarks: string;
  amount: number;
  sign_ind: number;
  curr_code: string;
  ex_rate: string;
  ac_name: string;
  ac_name_1: string;
  company_code: string;
  address_1: string;
  address_2: string;
  address_3: string;
  phone: string;
  fax: string;
  ref_no: string;
  ref_date: string;
  ac_code: string;
  bank_name: string;
  setup_ac_name: string;
  prepared: string;
  verified: string;
  approved: string;
  received: string;
  contact_person: string;
  payment_terms: string;
  qty: string;
  price: string;
  curr_sign: string;
  swift_code: string;
  lpo_no: string;
  lpo_date: string;
  party_name: string;
  party_address: string;
  party_phone: string;
  party_fax: string;
  tx_compnt_amt_1: string;
  ac_trn_no: string;
  tx_compnt_perc_1: string;
  tx_compnt_lcuramt_1: string;
  lcur_amount: string;
  company_trn_no: string;
  company_name: string;
  bank_name_inv: string;
  ac_code_inv: string;
  reference_no_inv: string;
  bank_address_inv: string;
  swift_code_inv: string;
};
export interface TTax {
  company_code: string;
  div_code: string;
  sr_no: number;
  tx_compnt_code: string;
  tx_cat_code: string;
  tx_subcat_code: string;
  tx_compntcat_code: string;
  tx_compntcat_name: string;
  tx_type: string;
  tx_percnt: number;
  tx_in_ac: string;
  tx_out_ac: string;
  tx_reverse_ac: string;
  tx_asset_ac: string;
  user_id: string;
  user_dt: Date;
}
export interface TAcSetup {
  company_code: string;
  pdc_receipt_code: string;
  pdc_issue_code: string;
  doc_date_editable: string;
  ac_code: string;
  bank_name: string;
  ac_name: string;
  swift_code: string;
  base_curr_code: string;
  price_decimal_nos: number;
  amount_decimal_nos: number;
  lcur_decimal_nos: number;
  qty_decimal_nos: number;
  financial_yr_start: Date;
  financial_yr_end: Date;
  doc_edit_from: Date;
  doc_edit_to: Date;
  job_class: string;
  exchange_diff_ac: string;
  principal_ac_group: string;
  expsubtype_accident: string;
  expsubtype_fine: string;
  expsubtype_fuel: string;
  expsubtype_ins: string;
  expsubtype_reg: string;
  expsubtype_repair: string;
  expsubtype_service: string;
  supplier_ac_group: string;
  expcode_vehicle: string;
  age_1: number;
  age_2: number;
  age_3: number;
  age_4: number;
  age_5: number;
  docno_type: string;
  intercompany_ac_group: string;
  multy_div_accounting: string;
  bill_settle_lcur: string;
  default_tax_bstype: string;
  age_6: number;
  updated_at: Date;
  updated_by: string;
  created_by: string;
  created_at: Date;
  tax_perc: number;
}
export type TTransactionHeader = {
  company_code: string;
  doc_type: string;
  doc_no: number;
  doc_date: string;
  ac_code: string;
  bank_ac_code: string;
  ref_no: string;
  ref_date: Date;
  remarks: string;
  curr_code: string;
  ex_rate: number;
  cheque_no: string;
  cheque_date: string;
  canceled: string;
  create_user: string;
  create_date: Date;
  last_serial_no: number;
  last_dtl_serial_no: number;
  payment_terms: string;
  lpo_no: string;
  lpo_date: Date;
  credit_period: number;
  due_date: Date;
  ref_doc_type: string;
  ac_payee: string;
  cheque_bank: string;
  party_name: string;
  party_address: string;
  party_phone: string;
  party_fax: string;
  remittance: string;
  auto_reverse: string;
  div_code: string;
  salesman_code: string;
  sector_code: string;
  sys_gen: string;
  tx_cat_code: string;
  tx_compntcat_code_1: string;
  tx_compntcat_code_2: string;
  tx_compntcat_code_3: string;
  tx_compntcat_code_4: string;
  tx_compnt_1_expmt: string;
  tx_tax_filed: string;
  tx_tax_filed_dt: Date;
  tx_tax_filed_refno: string;
  tx_compnt_hdisc_amt_1: number;
  doc_path: string;
  ref_doc_no: string;
  vat_trn_no: string;
  updated_at?: Date;
  updated_by?: string;
  created_by?: string;
  created_at?: Date;
};
export type TTransactionDocumentFrom = TTransactionHeader & {
  Account: TAccountChildren;
  MS_AC_BANKCODE: TBankTransaction & { Account: TAccountChildren };
  Currency: TCurrency;
  Division: TDivision;
  Accountsetup: { tax_perc: number };
};
export type TExpenseSubType = {
  company_code: string;
  exp_subtype_code: string;
  exp_subtype_description: string;
  exp_type_code: string;
  dept_code: string;
  updated_at?: Date;
  updated_by: string;
  created_by: string;
  created_at?: Date;
};
export type TExpenseType = {
  exp_code: string;
  exp_description: string;
  exp_type_code: string;
  company_code: string;
  ref_code: string;
  updated_at: Date;
  updated_by: string;
  created_by: string;
  created_at: Date;
};
export type TChequePayment = {
  company_code: string;
  ac_code: string;
  last_cheque_no: string;
  chq_template: string;
  words_length: number;
  bank_ac_code: string;
  bank_address: string;
  updated_at?: Date;
  updated_by?: string;
  created_by?: string;
  created_at?: Date;
};
