import oracledb from "oracledb";
import { Request, Response } from "express";
import { oracleDb } from "../../../../database/connection";
import constants from "../../../../helpers/constants";
import { QueryExecutor } from "../../../../database/QueryExecutor";

/* ================= helpers ================= */

const toDate = (d?: string | Date | null) =>
  d ? new Date(d).toISOString().split("T")[0] : null;

/* ================= exists ================= */

async function jobExists(
  COMPANY_CODE: string,
  JOB_TYPE: string,
  JOB_NO: string,
  conn: oracledb.Connection
): Promise<boolean> {
  const sql = `
    SELECT COUNT(*) CNT
    FROM TI_JOB
    WHERE COMPANY_CODE = :COMPANY_CODE
      AND JOB_TYPE = :JOB_TYPE
      AND JOB_NO = :JOB_NO
  `;
  const r: any = await QueryExecutor.execMaybe(sql, { COMPANY_CODE, JOB_TYPE, JOB_NO }, conn);
  return (r.rows?.[0]?.CNT || 0) > 0;
}

/* ================= INSERT (ALL COLUMNS) ================= */

async function insertTIJob(d: any, c: oracledb.Connection) {
const sql = `
INSERT INTO TI_JOB (
COMPANY_CODE,PRIN_CODE,JOB_NO,JOB_DATE,JOB_TYPE,JOB_CLASS,DEPT_CODE,
TRANSPORT_MODE,DOC_REF,PORT_CODE,DESCRIPTION1,DESCRIPTION2,
PRIN_REF1,PRIN_REF2,REMARKS,ETA,ATA,ETD,SCHEDULE_DATE,
PAYMENT_TERMS,CURR_CODE,EX_RATE,FRIEGHT_VALUE,INSURANCE_VALUE,
CUST_CODE,CONTAINER_FLAG,CONTAINER,CONTAINER_DATE,
PACKDET,PACKDET_DATE,ALLOCATED,ALLOCATE_DATE,
CANCELED,CANCEL_DATE,CONFIRMED,CONFIRM_DATE,
GRN_NO,GRN_DATE,INVOICED,INVOICE_DATE,
COMPLETED,COMPLETE_DATE,USER_ID,USER_DT,
EXP_JOBNO,PICKED,PICKED_DATE,ORDER_DATE,ORDERED,
DESTINATION_PORT,VESSEL_NAME,VOYAGE_NO,PAYABLEAT,
PLACE_RECEIPT,PLACE_DELIVERY,NO_OF_ORIGINAL_BL,BROKER_CODE,
QUOTATION_REF,BE_NO,BE_DATE,BE_DEP_AMOUNT,
DEPOSIT_COLLECTED,DEPOSIT_COLLECTED_DT,DEPOSIT_COLLECTED_NO,
BE_DEPOSITS,IND_FREIGHT,COUNTRY_ORIGIN,COUNTRY_DESTINATION,
TASK_ORDER,CUSTOM_RECNO,DOC_REF2,HAWB,REEXPORT,REF_JOBNO,
COMBINED_JOBNO,CARRIER,JOB_LOCK,COURIER_CODE,DELIVERY_POINT,
DEP_BATCHDATE,DEP_BATCHENTRY,DEP_DOC_TYPE,DEP_PERMIT_NO,
DEP_REMARKS,DEP_REMIT_NO,DOC_DEP_RCVD_DATE,DOC_DEPOSIT_AMT,
DOC_DEPOSIT_CURRENCY,DOC_DEPOSIT_DATE,DOC_DEPOSIT_RECEIVED,
DOC_DEPOSITD,DOC_REF_DATE,EXITBILL1,EXITBILL2,
JOB_INTEGRATION_CLASS,TOT_IMPORT_VALUE,REF_CUSTOMS,
REF_CUSTOMS_DATE,DRIVER_REF,DRIVER_REMARKS,DIV_CODE,
DOC_DEPOSIT_EXPIRY,SALESMAN_CODE,HEALTH_STATUS,
LETTER_UNDERTAKING,TRANSIT_TIME,DOCCUMENT_CHECK,
DELIVERY_REMARKS,DELIVERED_ON,CARGO_RECEIVED,
DELIVERED_BY,RECEIVED_DATE,CHECKLIST_NO,BACKORDER_PICK,
CANCELED_BY,CANCEL_REMARKS,SEND_MAIL,BACKLOG_MAIL,
DPLAN_FLAG,TRANS_BATCH_ID,SEND_MAIL_DN,KPI_INC,
KPI_EXC_REMARK,JOB_CATEGORY,EDIT_USER,TX_CAT_CODE,
BCF_CODE,DN_PRINT_DATE,DEC_TYPE,LAB_CODE,TEST_CODE,
DEC_DATE,DEC_NO,TALLY_TYPE,ORDER_SRNO,MEMBER_TYPE,
SALE_TYPE,FORWARDER_CODE,CONTR_DEPOSIT,CONTR_DEPOSIT_AMT,
TEMP_EXP,JOB_START_DATE,FEEDER_VESSEL_NAME,JOB_FLAG,
HOUSE_APPRTN,WALKIN_PRIN_CODE,UPDATED_BY,UPDATED_AT,
CREATED_BY,CREATED_AT
) VALUES (
:COMPANY_CODE,:PRIN_CODE,:JOB_NO,TO_DATE(:JOB_DATE,'YYYY-MM-DD'),
:JOB_TYPE,:JOB_CLASS,:DEPT_CODE,:TRANSPORT_MODE,:DOC_REF,
:PORT_CODE,:DESCRIPTION1,:DESCRIPTION2,:PRIN_REF1,:PRIN_REF2,
:REMARKS,TO_DATE(:ETA,'YYYY-MM-DD'),TO_DATE(:ATA,'YYYY-MM-DD'),
TO_DATE(:ETD,'YYYY-MM-DD'),TO_DATE(:SCHEDULE_DATE,'YYYY-MM-DD'),
:PAYMENT_TERMS,:CURR_CODE,:EX_RATE,:FRIEGHT_VALUE,:INSURANCE_VALUE,
:CUST_CODE,:CONTAINER_FLAG,:CONTAINER,
TO_DATE(:CONTAINER_DATE,'YYYY-MM-DD'),:PACKDET,
TO_DATE(:PACKDET_DATE,'YYYY-MM-DD'),:ALLOCATED,
TO_DATE(:ALLOCATE_DATE,'YYYY-MM-DD'),:CANCELED,
TO_DATE(:CANCEL_DATE,'YYYY-MM-DD'),:CONFIRMED,
TO_DATE(:CONFIRM_DATE,'YYYY-MM-DD'),
:GRN_NO,TO_DATE(:GRN_DATE,'YYYY-MM-DD'),
:INVOICED,TO_DATE(:INVOICE_DATE,'YYYY-MM-DD'),
:COMPLETED,TO_DATE(:COMPLETE_DATE,'YYYY-MM-DD'),
:USER_ID,SYSDATE,
:EXP_JOBNO,:PICKED,TO_DATE(:PICKED_DATE,'YYYY-MM-DD'),
TO_DATE(:ORDER_DATE,'YYYY-MM-DD'),:ORDERED,
:DESTINATION_PORT,:VESSEL_NAME,:VOYAGE_NO,:PAYABLEAT,
:PLACE_RECEIPT,:PLACE_DELIVERY,:NO_OF_ORIGINAL_BL,:BROKER_CODE,
:QUOTATION_REF,:BE_NO,TO_DATE(:BE_DATE,'YYYY-MM-DD'),
:BE_DEP_AMOUNT,:DEPOSIT_COLLECTED,
TO_DATE(:DEPOSIT_COLLECTED_DT,'YYYY-MM-DD'),
:DEPOSIT_COLLECTED_NO,:BE_DEPOSITS,:IND_FREIGHT,
:COUNTRY_ORIGIN,:COUNTRY_DESTINATION,:TASK_ORDER,
:CUSTOM_RECNO,:DOC_REF2,:HAWB,:REEXPORT,:REF_JOBNO,
:COMBINED_JOBNO,:CARRIER,:JOB_LOCK,:COURIER_CODE,
:DELIVERY_POINT,TO_DATE(:DEP_BATCHDATE,'YYYY-MM-DD'),
:DEP_BATCHENTRY,:DEP_DOC_TYPE,:DEP_PERMIT_NO,
:DEP_REMARKS,:DEP_REMIT_NO,
TO_DATE(:DOC_DEP_RCVD_DATE,'YYYY-MM-DD'),
:DOC_DEPOSIT_AMT,:DOC_DEPOSIT_CURRENCY,
TO_DATE(:DOC_DEPOSIT_DATE,'YYYY-MM-DD'),
:DOC_DEPOSIT_RECEIVED,:DOC_DEPOSITD,
TO_DATE(:DOC_REF_DATE,'YYYY-MM-DD'),
:EXITBILL1,:EXITBILL2,:JOB_INTEGRATION_CLASS,
:TOT_IMPORT_VALUE,:REF_CUSTOMS,
TO_DATE(:REF_CUSTOMS_DATE,'YYYY-MM-DD'),
:DRIVER_REF,:DRIVER_REMARKS,:DIV_CODE,
TO_DATE(:DOC_DEPOSIT_EXPIRY,'YYYY-MM-DD'),
:SALESMAN_CODE,:HEALTH_STATUS,
TO_DATE(:LETTER_UNDERTAKING,'YYYY-MM-DD'),
:TRANSIT_TIME,:DOCCUMENT_CHECK,
:DELIVERY_REMARKS,TO_DATE(:DELIVERED_ON,'YYYY-MM-DD'),
:CARGO_RECEIVED,:DELIVERED_BY,
TO_DATE(:RECEIVED_DATE,'YYYY-MM-DD'),
:CHECKLIST_NO,:BACKORDER_PICK,
:CANCELED_BY,:CANCEL_REMARKS,:SEND_MAIL,:BACKLOG_MAIL,
:DPLAN_FLAG,:TRANS_BATCH_ID,:SEND_MAIL_DN,:KPI_INC,
:KPI_EXC_REMARK,:JOB_CATEGORY,:EDIT_USER,:TX_CAT_CODE,
:BCF_CODE,TO_DATE(:DN_PRINT_DATE,'YYYY-MM-DD'),
:DEC_TYPE,:LAB_CODE,:TEST_CODE,
TO_DATE(:DEC_DATE,'YYYY-MM-DD'),
:DEC_NO,:TALLY_TYPE,:ORDER_SRNO,:MEMBER_TYPE,
:SALE_TYPE,:FORWARDER_CODE,:CONTR_DEPOSIT,
:CONTR_DEPOSIT_AMT,:TEMP_EXP,
TO_DATE(:JOB_START_DATE,'YYYY-MM-DD'),
:FEEDER_VESSEL_NAME,:JOB_FLAG,
:HOUSE_APPRTN,:WALKIN_PRIN_CODE,
:UPDATED_BY,SYSTIMESTAMP,
:CREATED_BY,SYSTIMESTAMP
)
`;
await QueryExecutor.execMaybe(sql, d, c);
}

/* ================= UPDATE (ALL COLUMNS) ================= */

async function updateTIJob(d: any, c: oracledb.Connection) {
const sql = `
UPDATE TI_JOB SET
PRIN_CODE=:PRIN_CODE,
JOB_DATE=TO_DATE(:JOB_DATE,'YYYY-MM-DD'),
JOB_CLASS=:JOB_CLASS,
DEPT_CODE=:DEPT_CODE,
TRANSPORT_MODE=:TRANSPORT_MODE,
DOC_REF=:DOC_REF,
PORT_CODE=:PORT_CODE,
DESCRIPTION1=:DESCRIPTION1,
DESCRIPTION2=:DESCRIPTION2,
PRIN_REF1=:PRIN_REF1,
PRIN_REF2=:PRIN_REF2,
REMARKS=:REMARKS,
ETA=TO_DATE(:ETA,'YYYY-MM-DD'),
ATA=TO_DATE(:ATA,'YYYY-MM-DD'),
ETD=TO_DATE(:ETD,'YYYY-MM-DD'),
SCHEDULE_DATE=TO_DATE(:SCHEDULE_DATE,'YYYY-MM-DD'),
PAYMENT_TERMS=:PAYMENT_TERMS,
CURR_CODE=:CURR_CODE,
EX_RATE=:EX_RATE,
FRIEGHT_VALUE=:FRIEGHT_VALUE,
INSURANCE_VALUE=:INSURANCE_VALUE,
CUST_CODE=:CUST_CODE,
CONTAINER_FLAG=:CONTAINER_FLAG,
CONTAINER=:CONTAINER,
CONTAINER_DATE=TO_DATE(:CONTAINER_DATE,'YYYY-MM-DD'),
PACKDET=:PACKDET,
PACKDET_DATE=TO_DATE(:PACKDET_DATE,'YYYY-MM-DD'),
ALLOCATED=:ALLOCATED,
ALLOCATE_DATE=TO_DATE(:ALLOCATE_DATE,'YYYY-MM-DD'),
CANCELED=:CANCELED,
CANCEL_DATE=TO_DATE(:CANCEL_DATE,'YYYY-MM-DD'),
CONFIRMED=:CONFIRMED,
CONFIRM_DATE=TO_DATE(:CONFIRM_DATE,'YYYY-MM-DD'),
GRN_NO=:GRN_NO,
GRN_DATE=TO_DATE(:GRN_DATE,'YYYY-MM-DD'),
INVOICED=:INVOICED,
INVOICE_DATE=TO_DATE(:INVOICE_DATE,'YYYY-MM-DD'),
COMPLETED=:COMPLETED,
COMPLETE_DATE=TO_DATE(:COMPLETE_DATE,'YYYY-MM-DD'),
EXP_JOBNO=:EXP_JOBNO,
PICKED=:PICKED,
PICKED_DATE=TO_DATE(:PICKED_DATE,'YYYY-MM-DD'),
ORDER_DATE=TO_DATE(:ORDER_DATE,'YYYY-MM-DD'),
ORDERED=:ORDERED,
DESTINATION_PORT=:DESTINATION_PORT,
VESSEL_NAME=:VESSEL_NAME,
VOYAGE_NO=:VOYAGE_NO,
PAYABLEAT=:PAYABLEAT,
PLACE_RECEIPT=:PLACE_RECEIPT,
PLACE_DELIVERY=:PLACE_DELIVERY,
NO_OF_ORIGINAL_BL=:NO_OF_ORIGINAL_BL,
BROKER_CODE=:BROKER_CODE,
QUOTATION_REF=:QUOTATION_REF,
BE_NO=:BE_NO,
BE_DATE=TO_DATE(:BE_DATE,'YYYY-MM-DD'),
BE_DEP_AMOUNT=:BE_DEP_AMOUNT,
DEPOSIT_COLLECTED=:DEPOSIT_COLLECTED,
DEPOSIT_COLLECTED_DT=TO_DATE(:DEPOSIT_COLLECTED_DT,'YYYY-MM-DD'),
DEPOSIT_COLLECTED_NO=:DEPOSIT_COLLECTED_NO,
BE_DEPOSITS=:BE_DEPOSITS,
IND_FREIGHT=:IND_FREIGHT,
COUNTRY_ORIGIN=:COUNTRY_ORIGIN,
COUNTRY_DESTINATION=:COUNTRY_DESTINATION,
TASK_ORDER=:TASK_ORDER,
CUSTOM_RECNO=:CUSTOM_RECNO,
DOC_REF2=:DOC_REF2,
HAWB=:HAWB,
REEXPORT=:REEXPORT,
REF_JOBNO=:REF_JOBNO,
COMBINED_JOBNO=:COMBINED_JOBNO,
CARRIER=:CARRIER,
JOB_LOCK=:JOB_LOCK,
COURIER_CODE=:COURIER_CODE,
DELIVERY_POINT=:DELIVERY_POINT,
DEP_BATCHDATE=TO_DATE(:DEP_BATCHDATE,'YYYY-MM-DD'),
DEP_BATCHENTRY=:DEP_BATCHENTRY,
DEP_DOC_TYPE=:DEP_DOC_TYPE,
DEP_PERMIT_NO=:DEP_PERMIT_NO,
DEP_REMARKS=:DEP_REMARKS,
DEP_REMIT_NO=:DEP_REMIT_NO,
DOC_DEP_RCVD_DATE=TO_DATE(:DOC_DEP_RCVD_DATE,'YYYY-MM-DD'),
DOC_DEPOSIT_AMT=:DOC_DEPOSIT_AMT,
DOC_DEPOSIT_CURRENCY=:DOC_DEPOSIT_CURRENCY,
DOC_DEPOSIT_DATE=TO_DATE(:DOC_DEPOSIT_DATE,'YYYY-MM-DD'),
DOC_DEPOSIT_RECEIVED=:DOC_DEPOSIT_RECEIVED,
DOC_DEPOSITD=:DOC_DEPOSITD,
DOC_REF_DATE=TO_DATE(:DOC_REF_DATE,'YYYY-MM-DD'),
EXITBILL1=:EXITBILL1,
EXITBILL2=:EXITBILL2,
JOB_INTEGRATION_CLASS=:JOB_INTEGRATION_CLASS,
TOT_IMPORT_VALUE=:TOT_IMPORT_VALUE,
REF_CUSTOMS=:REF_CUSTOMS,
REF_CUSTOMS_DATE=TO_DATE(:REF_CUSTOMS_DATE,'YYYY-MM-DD'),
DRIVER_REF=:DRIVER_REF,
DRIVER_REMARKS=:DRIVER_REMARKS,
DIV_CODE=:DIV_CODE,
DOC_DEPOSIT_EXPIRY=TO_DATE(:DOC_DEPOSIT_EXPIRY,'YYYY-MM-DD'),
SALESMAN_CODE=:SALESMAN_CODE,
HEALTH_STATUS=:HEALTH_STATUS,
LETTER_UNDERTAKING=TO_DATE(:LETTER_UNDERTAKING,'YYYY-MM-DD'),
TRANSIT_TIME=:TRANSIT_TIME,
DOCCUMENT_CHECK=:DOCCUMENT_CHECK,
DELIVERY_REMARKS=:DELIVERY_REMARKS,
DELIVERED_ON=TO_DATE(:DELIVERED_ON,'YYYY-MM-DD'),
CARGO_RECEIVED=:CARGO_RECEIVED,
DELIVERED_BY=:DELIVERED_BY,
RECEIVED_DATE=TO_DATE(:RECEIVED_DATE,'YYYY-MM-DD'),
CHECKLIST_NO=:CHECKLIST_NO,
BACKORDER_PICK=:BACKORDER_PICK,
CANCELED_BY=:CANCELED_BY,
CANCEL_REMARKS=:CANCEL_REMARKS,
SEND_MAIL=:SEND_MAIL,
BACKLOG_MAIL=:BACKLOG_MAIL,
DPLAN_FLAG=:DPLAN_FLAG,
TRANS_BATCH_ID=:TRANS_BATCH_ID,
SEND_MAIL_DN=:SEND_MAIL_DN,
KPI_INC=:KPI_INC,
KPI_EXC_REMARK=:KPI_EXC_REMARK,
JOB_CATEGORY=:JOB_CATEGORY,
EDIT_USER=:EDIT_USER,
TX_CAT_CODE=:TX_CAT_CODE,
BCF_CODE=:BCF_CODE,
DN_PRINT_DATE=TO_DATE(:DN_PRINT_DATE,'YYYY-MM-DD'),
DEC_TYPE=:DEC_TYPE,
LAB_CODE=:LAB_CODE,
TEST_CODE=:TEST_CODE,
DEC_DATE=TO_DATE(:DEC_DATE,'YYYY-MM-DD'),
DEC_NO=:DEC_NO,
TALLY_TYPE=:TALLY_TYPE,
ORDER_SRNO=:ORDER_SRNO,
MEMBER_TYPE=:MEMBER_TYPE,
SALE_TYPE=:SALE_TYPE,
FORWARDER_CODE=:FORWARDER_CODE,
CONTR_DEPOSIT=:CONTR_DEPOSIT,
CONTR_DEPOSIT_AMT=:CONTR_DEPOSIT_AMT,
TEMP_EXP=:TEMP_EXP,
JOB_START_DATE=TO_DATE(:JOB_START_DATE,'YYYY-MM-DD'),
FEEDER_VESSEL_NAME=:FEEDER_VESSEL_NAME,
JOB_FLAG=:JOB_FLAG,
HOUSE_APPRTN=:HOUSE_APPRTN,
WALKIN_PRIN_CODE=:WALKIN_PRIN_CODE,
UPDATED_BY=:UPDATED_BY,
UPDATED_AT=SYSTIMESTAMP
WHERE COMPANY_CODE=:COMPANY_CODE
AND JOB_TYPE=:JOB_TYPE
AND JOB_NO=:JOB_NO
`;
await QueryExecutor.execMaybe(sql, d, c);
}

/* ================= UPSERT ================= */

export async function upsertTIJob(data: any) {
  return oracleDb.withTransaction(async (conn) => {
    const exists = await jobExists(data.COMPANY_CODE, data.JOB_TYPE, data.JOB_NO, conn);
    if (exists) {
      await updateTIJob(data, conn);
      return "UPDATED";
    } else {
      await insertTIJob(data, conn);
      return "INSERTED";
    }
  });
}

/* ================= HANDLER ================= */

export const upsertTIJobHandler = async (req: Request, res: Response) => {
  try {
    const action = await upsertTIJob(req.body);
    res.status(constants.STATUS_CODES.OK).json({
      success: true,
      action,
      message: `TI_JOB ${action} successfully`
    });
  } catch (e: any) {
    res.status(500).json({
      success: false,
      message: e.message || "TI_JOB upsert failed"
    });
  }
};
