import { Save, Send, X } from "lucide-react";
import type { CSSProperties } from "react";
import { useCallback, useEffect, useState } from "react";
import { executeDynamicMutationColumn90, getDynamicLookup } from "../../api/lookups";
import { Button } from "../../components/ui/Button";
import { Dialog } from "../../components/ui/Dialog";
import { Input } from "../../components/ui/Input";
import { Select } from "../../components/ui/Select";
import { useAuth } from "../../state/AuthContext";

export type TApplicantInfo = {
  doc_no?: string | number | null;
  doc_type?: string;
  doc_date?: string;
  doc_ref_no?: string;
  cand_no?: string;
  cand_name?: string;
  pos_appl_for?: string;
  dept?: string;
  intvr_name?: string;
  intrvw_date?: string;
  hire_flag?: string;
  dept_head_comment1?: string;
  sign_1?: string;
  dept_head_comment2?: string;
  sign_2?: string;
  admin_hr_comment?: string;
  sign_3?: string;
  ceo_comment?: string;
  sign_4?: string;
};

type DeptOption = {
  dept_code: string;
  dept_short_name: string;
};

type FormMode = "add" | "edit" | "view";

type Props = {
  mode: FormMode;
  existingData?: Partial<TApplicantInfo>;
  onClose: (shouldRefetch?: boolean) => void;
};

function toDate(value: unknown): string {
  if (!value) return "";
  const normalized = String(value).trim();
  const date = new Date(normalized);
  return Number.isNaN(date.getTime()) ? "" : date.toISOString().slice(0, 10);
}

const today = new Date().toISOString().slice(0, 10);

// doc_no / doc_type are tracked but never surfaced as fields — doc_no is
// autogenerated by the backend and doc_type is always "INT" (interview),
// same as the old form.
const EMPTY: TApplicantInfo = {
  doc_no: null,
  doc_type: "INT",
  doc_date: today,
  doc_ref_no: "",
  cand_no: "",
  cand_name: "",
  pos_appl_for: "",
  dept: "",
  intvr_name: "",
  intrvw_date: "",
  hire_flag: "",
  dept_head_comment1: "",
  sign_1: "",
  dept_head_comment2: "",
  sign_2: "",
  admin_hr_comment: "",
  sign_3: "",
  ceo_comment: "",
  sign_4: "",
};

export function AddApplicantForm({ mode, existingData, onClose }: Props) {
  const { user } = useAuth();
  const readonly = mode === "view";
  const isEdit = mode === "edit";

  const [form, setForm] = useState<TApplicantInfo>({ ...EMPTY });
  const [errors, setErrors] = useState<Partial<Record<keyof TApplicantInfo, string>>>({});
  const [saving, setSaving] = useState(false);
  const [apiError, setApiError] = useState("");
  const [deptList, setDeptList] = useState<DeptOption[]>([]);
  const [confirmSubmitOpen, setConfirmSubmitOpen] = useState(false);

  // ── Load departments — parameter "HR_CAM_DEPARTMENT_DEPTCODE" ──────────
  const loadDepts = useCallback(async () => {
    try {
      const res = await getDynamicLookup({
        parameter: "HR_CAM_DEPARTMENT_DEPTCODE",
        loginid: user?.loginid ?? "",
        code1: user?.company_code ?? "",
        code2: "",
        code3: "",
        code4: "",
        number1: 0,
        number2: 0,
        number3: 0,
        number4: 0,
        date1: null,
        date2: null,
        date3: null,
        date4: null,
      });
      const list = Array.isArray(res) ? (res as Record<string, unknown>[]) : [];
      setDeptList(
        list.map((d) => ({
          dept_code: String(d.DEPT_CODE ?? d.dept_code ?? ""),
          dept_short_name: String(d.DEPT_SHORT_NAME ?? d.dept_short_name ?? ""),
        })),
      );
    } catch {
      // non-critical; dropdown will simply be empty
    }
  }, [user?.loginid, user?.company_code]);

  useEffect(() => {
    void loadDepts();
  }, [loadDepts]);

  // ── Populate form on edit / view ────────────────────────────────────────
  useEffect(() => {
    if ((isEdit || readonly) && existingData) {
      setForm({
        ...EMPTY,
        ...existingData,
        doc_date: toDate(existingData.doc_date) || today,
        intrvw_date: toDate(existingData.intrvw_date),
      });
    }
  }, [isEdit, readonly, existingData]);

  const set = (field: keyof TApplicantInfo, value: unknown) =>
    setForm((prev) => ({ ...prev, [field]: value }));

  // ── Validation ───────────────────────────────────────────────────────────
  const validate = (): boolean => {
    const next: Partial<Record<keyof TApplicantInfo, string>> = {};
    if (!form.doc_date) next.doc_date = "Doc Date is required";
    if (!form.cand_name?.trim()) next.cand_name = "Candidate Name is required";
    if (!form.dept?.trim()) next.dept = "Department is required";
    setErrors(next);
    return Object.keys(next).length === 0;
  };

  // ── Save — parameter "HR_APPLICANT_INFO_INS_UPD" ───────────────────────
  const handleSave = async () => {
    if (!validate()) return;
    setSaving(true);
    setApiError("");
    try {
      const docNo =
        isEdit && form.doc_no !== "" && form.doc_no != null
          ? Number(form.doc_no)
          : undefined;

      await executeDynamicMutationColumn90({
        parameter: "HR_APPLICANT_INFO_INS_UPD",
        loginid: user?.loginid ?? "",
        val1s1: user?.company_code ?? "",
        val1s2: form.doc_type ?? "INT",
        val1n1: docNo,
        val1s3: form.doc_ref_no || "",
        val1s4: form.cand_no || "",
        val1s5: form.cand_name || "",
        val1s6: form.pos_appl_for || "",
        val1s7: form.dept || "",
        val1s8: form.intvr_name || "",
        val1s9: form.intrvw_date ? toDate(form.intrvw_date) : "",
        val1s10: form.hire_flag || "",
        val1s11: form.dept_head_comment1 || "",
        val1s12: form.sign_1 || "",
        val1s13: form.dept_head_comment2 || "",
        val1s14: form.sign_2 || "",
        val1s15: form.admin_hr_comment || "",
        val1s16: form.sign_3 || "",
        val1s17: form.ceo_comment || "",
        val1s18: form.sign_4 || "",
        val1s19: toDate(form.doc_date),
        val1s20: isEdit ? "UPDATE" : "INSERT",
      });
      onClose(true);
    } catch (error) {
      setApiError(
        error instanceof Error ? error.message : "Unable to save applicant record",
      );
    } finally {
      setSaving(false);
    }
  };

  const handleSubmitClick = () => {
    if (!validate()) return;
    setConfirmSubmitOpen(true);
  };
  const confirmSubmit = async () => {
    setConfirmSubmitOpen(false);
    await handleSave();
  };

  // ── Field helpers (min-w-0 keeps grid children from forcing horizontal
  // overflow when a lookup value is wider than its column) ────────────────
  const field = (
    label: string,
    key: keyof TApplicantInfo,
    type: "text" | "date" = "text",
    required = false,
  ) => (
    <label className="field min-w-0" key={key}>
      <span>
        {label}
        {required && <strong className="text-destructive"> *</strong>}
      </span>
      <Input
        type={type}
        disabled={readonly}
        value={String(form[key] ?? "")}
        onChange={(e) => set(key, e.target.value)}
      />
      {errors[key] && <span className="text-destructive text-xs mt-0.5">{errors[key]}</span>}
    </label>
  );

  // Container-width-based grids (auto-fit/minmax) instead of Tailwind's
  // sm:/md: breakpoint classes. Breakpoint classes react to the BROWSER
  // WINDOW width, not the Dialog's actual rendered width — so if the
  // Dialog is narrower than the window's sm: breakpoint, Tailwind still
  // forces the wider column count and fields spill past the Dialog edge
  // and get clipped. auto-fit/minmax instead measures the real container
  // and only fits as many columns as actually have room, so it can never
  // overflow regardless of how the Dialog itself is sized.
  const topGridStyle: CSSProperties = {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    columnGap: "1rem",
    rowGap: "0.75rem",
    minWidth: 0,
  };
  const commentsGridStyle: CSSProperties = {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    columnGap: "1rem",
    rowGap: "0.75rem",
    minWidth: 0,
  };

  // ── UI ───────────────────────────────────────────────────────────────────
  return (
    // Flat, single flowing grid — no card sections, so the whole form fits
    // in one viewport with no vertical or horizontal scroll. overflow-x:
    // hidden is a safety net on top of the auto-fit grids below.
    <div className="grid gap-y-3" style={{ overflowX: "hidden", minWidth: 0 }}>
      {apiError && <div className="alert error">{apiError}</div>}

      {/* ── Row 1–2: core details — matches old UI layout exactly ──────── */}
      <div className="min-w-0" style={topGridStyle}>
        {field("Doc Date", "doc_date", "date", true)}
        {field("Doc Ref No", "doc_ref_no")}
        {field("Candidate Name", "cand_name", "text", true)}
        <label className="field min-w-0">
          <span>
            Department <strong className="text-destructive">*</strong>
          </span>
          <Select
            disabled={readonly}
            value={
              deptList.some((d) => d.dept_code === String(form.dept ?? ""))
                ? String(form.dept ?? "")
                : ""
            }
            onChange={(e) => set("dept", e.target.value)}
          >
            <option value="">-- Select Department --</option>
            {deptList.map((d) => (
              <option key={d.dept_code} value={d.dept_code}>
                {d.dept_code} - {d.dept_short_name}
              </option>
            ))}
          </Select>
          {errors.dept && <span className="text-destructive text-xs mt-0.5">{errors.dept}</span>}
        </label>

        {field("Position Applied", "pos_appl_for")}
        {field("Interviewer Name", "intvr_name")}
        {field("Interview Date", "intrvw_date", "date")}
        <label className="field min-w-0">
          <span>Hire</span>
          <Select
            disabled={readonly}
            value={form.hire_flag ?? ""}
            onChange={(e) => set("hire_flag", e.target.value)}
          >
            <option value="">-- Select --</option>
            <option value="Y">Yes</option>
            <option value="N">No</option>
          </Select>
        </label>
      </div>

      <hr className="border-border" />

      {/* ── Comments & signatories — matches old UI layout exactly ─────── */}
      <div className="min-w-0" style={commentsGridStyle}>
        {field("Dept Head Comment 1", "dept_head_comment1")}
        {field("Sign 1", "sign_1")}
        {field("Dept Head Comment 2", "dept_head_comment2")}
        {field("Sign 2", "sign_2")}
        {field("Admin HR Comment", "admin_hr_comment")}
        {field("Sign 3", "sign_3")}
        {field("CEO Comment", "ceo_comment")}
        {field("Sign 4", "sign_4")}
      </div>

      {/* ── Actions ──────────────────────────────────────────────────────── */}
      <div className="flex flex-wrap justify-end gap-2 border-t pt-3">
        <Button variant="outline" onClick={() => onClose(false)}>
          <X size={15} /> {readonly ? "Close" : "Cancel"}
        </Button>
        {!readonly && (
          <>
            <Button variant="outline" disabled={saving} onClick={handleSave}>
              <Save size={15} /> {saving ? "Saving..." : "Save as Draft"}
            </Button>
            <Button disabled={saving} onClick={handleSubmitClick}>
              <Send size={15} /> Submit
            </Button>
          </>
        )}
      </div>

      {/* ── Submit confirmation ──────────────────────────────────────────── */}
      <Dialog
        open={confirmSubmitOpen}
        title="Submit"
        description="Are you sure you want to Submit?"
        compact
        onClose={() => setConfirmSubmitOpen(false)}
        footer={
          <>
            <Button variant="outline" onClick={() => setConfirmSubmitOpen(false)}>
              No
            </Button>
            <Button onClick={confirmSubmit} disabled={saving}>
              Yes
            </Button>
          </>
        }
      >
        <p className="text-sm text-muted-foreground">
          This will submit the applicant record for{" "}
          <strong>{form.cand_name || "(new candidate)"}</strong>.
        </p>
      </Dialog>
    </div>
  );
}