
import type { HrMasterConfig } from "./HrMasterPage";
import { getDynamicLookup } from "../../api/lookups";
import { getWmsMaster } from "../../api/wms";

const yesNo = [
  { label: "No", value: "N" },
  { label: "Yes", value: "Y" },
];

const activeInactive = [
  { label: "Active", value: "A" },
  { label: "Inactive", value: "N" },
];

const dynamicList = (parameter: string, useCompany = false) => (context: { loginid: string; companyCode: string }) => ({
  parameter,
  loginid: context.loginid,
  code1: useCompany ? context.companyCode : "",
  code2: "",
});

const text = (form: Record<string, unknown>, key: string, fallback = "") => String(form[key] ?? fallback);
const num = (form: Record<string, unknown>, key: string) => {
  const value = Number(form[key]);
  return Number.isFinite(value) ? value : undefined;
};
const dateText = (form: Record<string, unknown>, key: string) => text(form, key);

const countryLookup = {
  columns: [
    { field: "country_code", header: "Code" },
    { field: "country_name", header: "Country" },
  ],
  valueField: "country_code",
  displayFields: ["country_code", "country_name"],
  loadOptions: async () => (await getWmsMaster("country", { page: 1, limit: 100000 })).tableData,
};



const mainBankLookup = {
  columns: [
    { field: "main_bank_code", header: "Code" },
    { field: "main_bank_name", header: "Bank Name" },
    { field: "main_bank_short_name", header: "Short Name" },
  ],
  valueField: "main_bank_code",
  displayFields: ["main_bank_code", "main_bank_name"],
  loadOptions: (context: { loginid: string; companyCode: string }) =>
    getDynamicLookup({
      parameter: "MST_HR_Main_Bank",
      loginid: context.loginid,
      code1: context.companyCode,
      code2: "",
      code3: "",
      code4: "",
      number1: 0,
      number2: 0,
      number3: 0,
      number4: 0,
      date1: null,
      date2: null,
      date3: null,
      date4: null,
    }),
};



// const religionLookup = {
//   columns: [
//     { field: "religion_code", header: "Code" },
//     { field: "religion_name", header: "Religion Name" },
//   ],
//   valueField: "religion_code",
//   displayFields: ["religion_code", "religion_name"],
//   loadOptions: (context: { loginid: string; companyCode: string }) =>
//     getDynamicLookup({
//       parameter: "MST_HR_MS_HR_RELIGION",
//       loginid: context.loginid,
//       code1: context.companyCode,
//       code2: "",
//     }),
// };

const religionLookup = {
  columns: [
    { field: "religion_code", header: "Code" },
    { field: "religion_name", header: "Religion Name" },
  ],
  valueField: "religion_code",
  displayFields: ["religion_code", "religion_name"],
  loadOptions: (context: { loginid: string; companyCode: string }) =>
    getDynamicLookup({
      parameter: "MST_HR_MS_HR_RELIGION",
      loginid: context.loginid,
      code1: context.companyCode,
      code2: "",
    }),
};


export const hrMasterConfigs: Record<string, HrMasterConfig> = {
  department: {
    title: "Department Master",
    subtitle: "Maintain HR departments, division link, department head, address and contact details.",
    master: "hrDepartment",
    gmEndpoint: "department",
    routeKeys: ["hrdepartment", "hr_department", "department"],
    keyField: "dept_code",
    fields: [
      { name: "dept_code", label: "Department Code", required: true, disabledOnEdit: true, width: 160 },
      { name: "dept_name", label: "Department Name", required: true, width: 260 },
      { name: "dept_short_name", label: "Short Name", required: true, width: 140 },
      { name: "div_code", label: "Division", required: true, width: 130 },
      { name: "dept_head_id", label: "Department Head", width: 160 },
      { name: "phone", label: "Phone", width: 150 },
      { name: "email", label: "Email", type: "email", width: 220 },
      { name: "status", label: "Status", type: "select", options: yesNo, required: true, width: 120 },
      { name: "dept_addr1", label: "Address 1", table: false },
      { name: "dept_addr2", label: "Address 2", table: false },
      { name: "dept_addr3", label: "Address 3", table: false },
      { name: "fax", label: "Fax", table: false },
      { name: "enterprice_code", label: "Enterprise Code", table: false },
      { name: "remarks", label: "Remarks", table: false },
    ],
    defaults: { status: "Y" },
    deleteMode: "master",
  },
  division: {
    title: "Division Master",
    subtitle: "Maintain HR divisions, payroll settings, contacts and invoice bank details.",
    master: "hrDivision",
    gmEndpoint: "division",
    routeKeys: ["hrdivision", "hr_division", "division"],
    keyField: "div_code",
    fields: [
      { name: "div_code", label: "Division Code", required: true, disabledOnEdit: true, width: 150 },
      { name: "div_name", label: "Division Name", required: true, width: 260 },
      { name: "div_short_name", label: "Short Name", required: true, width: 140 },
      { name: "country_code", label: "Country", lookup: countryLookup, width: 120 },
      { name: "div_head_id", label: "Division Head", width: 150 },
      { name: "phone", label: "Phone", width: 150 },
      { name: "email", label: "Email", type: "email", width: 220 },
      { name: "status", label: "Status", type: "select", options: yesNo, required: true, width: 120 },
      { name: "payroll_status", label: "Payroll Status", width: 150 },
      { name: "pay_month", label: "Pay Month", type: "number", width: 120 },
      { name: "pay_year", label: "Pay Year", type: "number", width: 120 },
      { name: "normal_working_hrs", label: "Normal Working Hours", type: "number", table: false },
      { name: "payroll_date", label: "Payroll Date", type: "date", table: false },
      { name: "payroll_cutoff_date", label: "Payroll Cutoff Date", type: "date", table: false },
      { name: "div_address1", label: "Address 1", table: false },
      { name: "div_address2", label: "Address 2", table: false },
      { name: "div_address3", label: "Address 3", table: false },
      { name: "bank_name_inv", label: "Invoice Bank", table: false },
      { name: "ac_code_inv", label: "Invoice A/C Code", table: false },
      { name: "swift_code_inv", label: "Swift Code", table: false },
      { name: "remarks", label: "Remarks", table: false },
    ],
    defaults: { status: "Y" },
    deleteMode: "master",
  },
  airport: {
    title: "Airport Master",
    subtitle: "Maintain airport codes, fare class, ticket fares, currency and destination country.",
    master: "hrAirport",
    gmEndpoint: "airport",
    routeKeys: ["hrairport", "hr_airport", "airport"],
    keyField: "airport_code",
    fields: [
      { name: "airport_code", label: "Airport Code", required: true, disabledOnEdit: true, width: 150 },
      { name: "airport_name", label: "Airport Name", required: true, width: 260 },
      { name: "airport_short_name", label: "Short Name", width: 140 },
      { name: "fair_class", label: "Fare Class", required: true, width: 120 },
      { name: "adult_ticket_fair", label: "Adult Fare", type: "number", required: true, width: 130 },
      { name: "curr_code", label: "Currency", width: 120 },
      { name: "ex_rate", label: "Exchange Rate", type: "number", width: 140 },
      { name: "destination_country", label: "Destination Country", width: 170 },
      { name: "status", label: "Status", type: "select", options: activeInactive, width: 120 },
      { name: "fc_adult_fair", label: "First Class Adult Fare", type: "number", table: false },
      { name: "fc_child_fair", label: "First Class Child Fare", type: "number", table: false },
      { name: "fc_infant_fair", label: "First Class Infant Fare", type: "number", table: false },
      { name: "remarks", label: "Remarks", table: false },
    ],
    defaults: { status: "A", fair_class: "E", adult_ticket_fair: 0, ex_rate: 1 },
    deleteMode: "master",
  },
  employeestatus: {
    title: "Employee Status Master",
    subtitle: "Maintain employee status codes used by employee and HR flow screens.",
    master: "hrEmployeeStatus",
    gmEndpoint: "employeestatus",
    routeKeys: ["hremployeestatus", "hr_employee_status", "employee_status", "empstatus"],
    keyField: "empstatus_code",
    fields: [
      { name: "empstatus_code", label: "Status Code", required: true, disabledOnEdit: true, width: 140 },
      { name: "empstatus_name", label: "Status Name", required: true, width: 260 },
      { name: "empstatus_short_desc", label: "Short Description", width: 170 },
      { name: "remarks", label: "Remarks", width: 280 },
    ],
    deleteMode: "master",
  },
  bank: {
    title: "Bank Master",
    subtitle: "Maintain HR bank code, address, contact, company account and remarks.",
    master: "bank",
    gmEndpoint: "bank",
    routeKeys: ["bank", "bank_master", "banks_master", "main_bank", "main_banks", "hrbank", "hr_bank"],
    keyField: "main_bank_code",  
    source: "dynamic",
    mutationMode: "column90",
    listQuery: (context) => ({
        parameter: "MST_HR_Main_Bank",
        loginid: context.loginid,
        code1: context.companyCode,
        code2: "",
        code3: "",
        code4: "",
        number1: 0,
        number2: 0,
        number3: 0,
        number4: 0,
        date1: null,
        date2: null,
        date3: null,
        date4: null,
    }),

buildSave: (form, context) => {
    console.log("_edit_key:", form._edit_key);
    console.log("main_bank_code:", form.main_bank_code);
    return {
        parameter: "mst_hr_main_bank_ins_upd",
        loginid: context.loginid,
        val1s1: context.companyCode,
        val1s2: form._edit_key
    ? String(form._edit_key)           
    : text(form, "main_bank_code"),    
val1s18: form._edit_key
    ? text(form, "main_bank_code")     
    : "",    
        val1s3: text(form, "main_bank_name"),
        val1s4: text(form, "main_bank_short_name"),
        val1s5: text(form, "main_bank_addr1"),
        val1s6: text(form, "main_bank_addr2"),
        val1s7: text(form, "main_bank_addr3"),
        val1s8: text(form, "country_code"),
        val1s9: text(form, "phone"),
        val1s10: text(form, "fax"),
        val1s11: text(form, "email"),
        val1s12: text(form, "current_acc_code"),
        val1s13: text(form, "payer_bk_short_name"),
        val1s14: text(form, "remarks"),
        val1s15: text(form, "payer_ac_iban"),
        val1s16: text(form, "status", "A"),
        val1s17: text(form, "bk_bic_swift"),
    };
},
buildDelete: (row, context) => ({
        parameter: "MST_HR_DEL_MAIN_BANK",
        loginid: context.loginid,
        code1: context.companyCode,
        code2: text(row, "main_bank_code")
    }),
    fields: [
        { name: "main_bank_name", label: "Bank Name", required: true, width: 280 },
        { name: "main_bank_code", label: "Bank Code",required: true, width: 140 },
        { name: "main_bank_short_name", label: "Short Name", width: 150 },
       
        { name: "payer_bk_short_name", label: "Bank Short Name", table: false },
        { name: "payer_ac_iban", label: "Bank IBAN", table: false },
        { name: "bk_bic_swift", label: "Bank BIC/Swift", table: false },
      
        { name: "main_bank_addr1", label: "Address", required: true, table: false },
        { name: "main_bank_addr2", label: "Address 2", table: false },
        { name: "main_bank_addr3", label: "Address 3", table: false },
        { name: "country_code", label: "Country Code", lookup: countryLookup, required: true, table: false },
        { name: "phone", label: "Phone", table: false },
        { name: "fax", label: "Fax", table: false },
        { name: "email", label: "Email", type: "email", table: false },

        { name: "remarks", label: "Remarks", table: false },
        { name: "status", label: "Status", type: "select", options: activeInactive, required: true, table: false },
    ],
    defaults: { status: "A" },
    deleteMode: "master",
},

hrbank: {
    title: "Bank",
    subtitle: "Maintain HR bank code, address, contact and remarks.",
    master: "hrbank",
    gmEndpoint: "hrbank",
    routeKeys: ["hrbank", "hr_bank", "bank", "banks"],
    keyField: "bank_code",
    source: "dynamic",
    mutationMode: "column90",
    listQuery: (context) => ({
        parameter: "MST_HR_Bank",
        loginid: context.loginid,
        code1: context.companyCode,
        code2: "",
        code3: "",
        code4: "",
        number1: 0,
        number2: 0,
        number3: 0,
        number4: 0,
        date1: null,
        date2: null,
        date3: null,
        date4: null,
    }),
    buildSave: (form, context) => ({
        parameter: "mst_hr_bank_ins_upd",
        loginid: context.loginid,
        val1s1: context.companyCode,
         val1s2: form._edit_key
        ? String(form._edit_key)
        : "",  
        val1s3: text(form, "bank_name"),
        val1s4: text(form, "bank_short_name"),
        val1s5: text(form, "main_bank_code"),
        val1s6: text(form, "company_flag", "N"),
        val1s7: text(form, "bank_addr1"),
        val1s8: text(form, "bank_addr2"),
        val1s9: text(form, "bank_addr3"),
        val1s10: text(form, "country_code"),
        val1s11: text(form, "phone"),
        val1s12: text(form, "fax"),
        val1s13: text(form, "email"),
        val1s14: text(form, "comp_acct_code"),
        val1s15: text(form, "remarks"),
        val1s16: text(form, "status", "A"),
        val1s17: form._edit_key
            ? text(form, "bank_code")
            : "",
    }),
    buildDelete: (row, context) => ({
        parameter: "MST_HR_DEL_BANK",
        loginid: context.loginid,
        code1: context.companyCode,
        code2: text(row, "bank_code"),
    }),
    fields: [
      
      { name: "bank_code", label: "Bank Code", hideOnAdd: true, disabledOnEdit: true, width: 140 },
        { name: "bank_name", label: "Bank Name", required: true, width: 280 },
        { name: "bank_short_name", label: "Short Name", width: 150 },
        { name: "main_bank_code", label: "Main Bank Code", width: 160, table: false, required: true, lookup: mainBankLookup },
        { name: "company_flag", label: "Company Branch", type: "select", options: yesNo, width: 150, table: false },

       
        { name: "bank_addr1", label: "Address", required: true, table: false },
        { name: "bank_addr2", label: "Address 2", table: false },
        { name: "bank_addr3", label: "Address 3", table: false },
        { name: "country_code", label: "Country Code", lookup: countryLookup, required: true, table: false },
        { name: "phone", label: "Phone", table: false },
        { name: "fax", label: "Fax", table: false },
        { name: "email", label: "Email", type: "email", table: false },
        { name: "remarks", label: "Remarks", table: false },
        { name: "status", label: "Status", type: "select", options: activeInactive, required: true, table: false },
    ],
    defaults: { status: "A", company_flag: "N" },
    deleteMode: "master",
},
  
  sponsor: {
    title: "Sponsor Master",
    subtitle: "Maintain sponsor trade license, immigration, visa allocation and block status.",
    master: "hrSponsor",
    gmEndpoint: "sponsor",
    routeKeys: ["sponsor", "hrsponsor", "hr_sponsor"],
    keyField: "sponsor_code",
    source: "dynamic",
    mutationMode: "column90",
    listQuery: (context) => ({
      parameter: "HR_SPONSOR_SELECT",
      loginid: context.loginid,
      code1: context.companyCode,
      code2: "",
      code3: "",
      code4: "",
      number1: 0,
      number2: 0,
      number3: 0,
      number4: 0,
      date1: null,
      date2: null,
      date3: null,
      date4: null,
    }),
    buildSave: (form, context) => ({
      parameter: "hr_sponsor_ins_upd",
      loginid: context.loginid,
      val1s1: context.companyCode,
      val1s2: text(form, "sponsor_code"),
      val1s3: text(form, "sponsor_name"),
      val1s4: text(form, "sponsor_short_name"),
      val1s5: text(form, "trade_license_no"),
      val1s6: dateText(form, "trade_license_exp_date"),
      val1s7: text(form, "sponsor_address1"),
      val1s8: text(form, "sponsor_address2"),
      val1s9: text(form, "country_code"),
      val1s10: text(form, "sponsor_labor_no"),
      val1s11: text(form, "sponsor_immgr_no"),
      val1s12: dateText(form, "sponsor_immgr_dt"),
      val1s13: text(form, "labour_card_blocked", "N"),
      val1s14: text(form, "blocked_reason"),
      val1s15: text(form, "remarks"),
      val1s16: text(form, "status", "A"),
      val1n1: num(form, "no_of_visa") || 0,
      val1n2: num(form, "no_of_visit_visa") || 0,
    }),
    buildDelete: (row, context) => ({ parameter: "MST_HR_DEL_SPONSOR", loginid: context.loginid, code1: context.companyCode, code2: text(row, "sponsor_code") }),
    fields: [
      { name: "sponsor_code", label: "Sponsor Code", required: true, disabledOnEdit: true, width: 150 },
      { name: "sponsor_name", label: "Sponsor Name", required: true, width: 280 },
      { name: "sponsor_short_name", label: "Short Name", width: 140 },
      { name: "trade_license_no", label: "Trade License No", width: 160 },
      { name: "trade_license_exp_date", label: "License Expiry", type: "date", width: 150 },
      { name: "country_code", label: "Country", lookup: countryLookup, width: 120 },
      { name: "no_of_visa", label: "No of Visa", type: "number", width: 130 },
      { name: "no_of_visit_visa", label: "Visit Visa", type: "number", width: 130 },
      { name: "sponsor_labor_no", label: "Labor No", width: 140 },
      { name: "sponsor_immgr_no", label: "Immigration No", required: true, width: 160 },
      { name: "sponsor_immgr_dt", label: "Immigration Date", type: "date", width: 150 },
      { name: "labour_card_blocked", label: "Blocked", type: "select", options: yesNo, width: 120 },
      { name: "status", label: "Status", type: "select", options: activeInactive, required: true, width: 120 },
      { name: "sponsor_address1", label: "Address 1", table: false },
      { name: "sponsor_address2", label: "Address 2", table: false },
      { name: "blocked_reason", label: "Blocked Reason", table: false },
      { name: "remarks", label: "Remarks", table: false },
    ],
    defaults: { status: "A", labour_card_blocked: "N", no_of_visa: 0, no_of_visit_visa: 0 },
    deleteMode: "master",
  },
  contract: {
    title: "Contract Type Master",
    subtitle: "Maintain employee contract type descriptions and active status.",
    master: "hrContract",
    gmEndpoint: "contract",
    routeKeys: ["contract", "contracttype", "contract_type", "contract_types", "hrcontract"],
    keyField: "contract_type",
    source: "dynamic",
    listQuery: (context) => ({
      parameter: "HR_CONTRACT_TYPES_SELECT",
      loginid: context.loginid,
      code1: context.companyCode,
      code2: "",
      code3: "",
      code4: "",
      number1: 0,
      number2: 0,
      number3: 0,
      number4: 0,
      date1: null,
      date2: null,
      date3: null,
      date4: null,
    }),
    buildSave: (form, context) => ({
      parameter: "MST_HR_CONTRACT_TYPES",
      loginid: context.loginid,
      val1s1: context.companyCode,
      val1s2: text(form, "contract_type"),
      val1s3: text(form, "contract_type_desc"),
      val1s4: text(form, "contract_type_short_desc"),
      val1s5: text(form, "remarks"),
      val1s6: text(form, "status", "A"),
    }),
    buildDelete: (row, context) => ({ parameter: "MST_HR_DEL_CONTRACT_TYPES", loginid: context.loginid, code1: context.companyCode, code2: text(row, "contract_type") }),
    fields: [
      { name: "contract_type", label: "Contract Type", required: true, disabledOnEdit: true, width: 150 },
      { name: "contract_type_desc", label: "Description", required: true, width: 280 },
      { name: "contract_type_short_desc", label: "Short Description", width: 170 },
      { name: "status", label: "Status", type: "select", options: activeInactive, required: true, width: 120 },
      { name: "remarks", label: "Remarks", width: 260 },
    ],
    defaults: { status: "A" },
    deleteMode: "master",
  },

 religion: {
  title: "Religion Master",
  subtitle: "Maintain religion codes, names, short names, remarks, and active status.",
  master: "religion",
  gmEndpoint: "religion",
  routeKeys: ["religion", "hr_religion"],
  keyField: "religion_code",
  source: "dynamic",

  listQuery: (context) => ({
    parameter: "MST_HR_MS_HR_RELIGION",
    loginid: context.loginid,
    code1: context.companyCode,
    code2: "",
    code3: "",
    code4: "",
    number1: 0,
    number2: 0,
    number3: 0,
    number4: 0,
    date1: null,
    date2: null,
    date3: null,
    date4: null,
  }),

  buildSave: (form, context) => ({
    parameter: "MST_HR_RELIGION",
    loginid: context.loginid,
    val1s1: context.companyCode,
    val1s2: text(form, "religion_code", "0") || "0",
    val1s3: text(form, "religion_name"),
    val1s4: text(form, "religion_short_name"),
    val1s5: text(form, "remarks"),
    val1s6: text(form, "status", "A"),
  }),

  buildDelete: (row, context) => ({
    parameter: "MST_HR_DEL_RELIGION",
    loginid: context.loginid,
    code1: context.companyCode,
    code2: text(row, "religion_code"),
  }),

  fields: [
    {
      name: "religion_code",
      label: "Religion Code",
      disabledOnEdit: true,
      disabledOnAdd: true,
      width: 150,
    },
    {
      name: "religion_name",
      label: "Religion Name",
      required: true,
      width: 260,
    },
    {
      name: "religion_short_name",
      label: "Short Name",
      width: 140,
    },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: activeInactive,
      width: 120,
    },
    {
      name: "remarks",
      label: "Remarks",
      width: 260,
    },
  ],

  defaults: {
    status: "A",
  },

  deleteMode: "master",
},
  caste: {
    title: "Caste Master",
    subtitle: "Maintain caste records linked to religion, with short name, remarks, and status.",
    master: "caste",
    gmEndpoint: "caste",
    routeKeys: ["caste", "hr_caste"],
    keyField: "caste_code",
    source: "dynamic",
    listQuery: dynamicList("MST_HR_MS_HR_CASTE",true),
    autoGenerateKey: true,
    buildSave: (form, context) => ({
  parameter: "MST_HR_CASTE",
  loginid: context.loginid,

  val1s1: context.companyCode,
  val1s2: text(form, "caste_code", "0") || "0",
  val1s3: text(form, "religion_code"),
  val1s4: text(form, "caste_name"),
  val1s5: text(form, "caste_short_name"),
  val1s6: text(form, "remarks"),
  val1s7: text(form, "status", "A"),
}),
buildDelete: (row, context) => ({
  parameter: "MST_HR_DEL_CASTE",
  loginid: context.loginid,
  code1: context.companyCode,
  code2: text(row, "caste_code"),
  code3: text(row, "religion_code"),
}),    fields: [
    { name: "caste_code", label: "Caste Code", disabledOnEdit: true, disabledOnAdd: true, width: 140 },
      // { name: "religion_code", label: "Religion Code", required: true, disabledOnEdit: true, width: 150 },
      { name: "religion_code", label: "Religion", required: true, lookup: religionLookup, width: 150 },
      { name: "caste_name", label: "Caste Name", required: true, width: 260 },
      { name: "caste_short_name", label: "Short Name", width: 150 },
      { name: "status", label: "Status", type: "select", options: activeInactive, width: 120 },
      { name: "remarks", label: "Remarks", width: 280 },
    ],
    defaults: { status: "A" },
    deleteMode: "master",
  },
  educational_level: {
    title: "Educational Level Master",
    subtitle: "Maintain education level descriptions used in HR employee profiles.",
    master: "educational_level",
    gmEndpoint: "educational_level",
    routeKeys: ["educational_level", "education_level", "edulevel", "edu_level"],
    keyField: "edu_level_code",
    source: "dynamic",
    listQuery: dynamicList("HR_EDUCATIONAL_LEVEL_SELECT", true),
    autoGenerateKey: true,
    buildSave: (form, context) => ({
  parameter: "MST_HR_EDU_LEVEL",
  loginid: context.loginid,
  val1s1: context.companyCode,
  val1s2: text(form, "edu_level_code"),
  val1s3: text(form, "edu_level_desc"),
  val1s4: text(form, "edu_level_short_desc"),
  val1s5: text(form, "remarks"),
  val1s6: text(form, "status", "A"),
}),
buildDelete: (row, context) => ({
  parameter: "MST_HR_DEL_EDU_LEVEL",
  loginid: context.loginid,
  code1: context.companyCode,
  code2: text(row, "edu_level_code"),
}),    fields: [
      { name: "edu_level_code", label: "Level Code", required: true, disabledOnEdit: true, width: 140 },
      { name: "edu_level_desc", label: "Level Description", required: true, width: 280 },
      { name: "edu_level_short_desc", label: "Short Description", width: 170 },
      { name: "status", label: "Status", type: "select", options: activeInactive, width: 120 },
      { name: "remarks", label: "Remarks", width: 280 },
    ],
    defaults: { status: "A" },
    deleteMode: "master",
  },
  educational_discipline: {
    title: "Educational Discipline Master",
    subtitle: "Maintain educational discipline codes, descriptions, remarks, and status.",
    master: "educational_discipline",
    gmEndpoint: "educational_discipline",
    routeKeys: ["educational_discipline", "education_discipline", "edu_discipline"],
    keyField: "edu_disc_code",
    source: "dynamic",
    listQuery: dynamicList("MST_HR_MS_HR_EDU_DISCIPLINE",true),
    autoGenerateKey: true,
    buildSave: (form, context) => ({
      parameter: "MST_HR_EDU_DISCIPLINE",
      loginid: context.loginid,
      val1s1: text(form, "edu_disc_code"),
      val1s2: text(form, "edu_disc_desc"),
      val1s3: text(form, "edu_disc_short_desc"),
      val1s4: text(form, "remarks"),
      val1s5: text(form, "status", "A"),
      val1s6: context.companyCode,
    }),
buildDelete: (row, context) => ({
  parameter: "MST_HR_DEL_EDU_DISCIPLINE",
  loginid: context.loginid,
  code1: context.companyCode,
  code2: text(row, "edu_disc_code"),
}),    fields: [
      { name: "edu_disc_code", label: "Discipline Code", required: true, disabledOnEdit: true, width: 160 },
      { name: "edu_disc_desc", label: "Discipline Description", required: true, width: 300 },
      { name: "edu_disc_short_desc", label: "Short Description", width: 170 },
      { name: "status", label: "Status", type: "select", options: activeInactive, width: 120 },
      { name: "remarks", label: "Remarks", width: 280 },
    ],
    defaults: { status: "A" },
    deleteMode: "master",
  },
  languages: {
    title: "Language Master",
    subtitle: "Maintain language codes, descriptions, remarks, and active status.",
    master: "languages",
    gmEndpoint: "languages",
    routeKeys: ["languages", "language", "hr_languages"],
    keyField: "lang_code",
    source: "dynamic",
    listQuery: dynamicList("MST_HR_MS_HR_LANGUAGES",true),
    autoGenerateKey: true,
    buildSave: (form, context) => ({
      parameter: "MST_HR_LANGUAGES",
      loginid: context.loginid,
      code1: context.companyCode,
      val1s1: text(form, "lang_code"),
      val1s2: text(form, "lang_desc"),
      val1s3: text(form, "lang_short_desc"),
      val1s4: text(form, "remarks"),
      val1s5: text(form, "status", "A"),
      val1s6: context.companyCode,
    }),
buildDelete: (row, context) => ({
  parameter: "MST_HR_DEL_LANGUAGES",
  loginid: context.loginid,
  code1: context.companyCode,
  code2: text(row, "lang_code"),
}),    fields: [
      { name: "lang_code", label: "Language Code", required: true, disabledOnEdit: true, width: 150 },
      { name: "lang_desc", label: "Language Description", required: true, width: 280 },
      { name: "lang_short_desc", label: "Short Description", width: 170 },
      { name: "status", label: "Status", type: "select", options: activeInactive, width: 120 },
      { name: "remarks", label: "Remarks", width: 280 },
    ],
    defaults: { status: "A" },
    deleteMode: "master",
  },
  skills: {
    title: "Skill Master",
    subtitle: "Maintain HR skill codes, categories, descriptions, remarks, and status.",
    master: "skills",
    gmEndpoint: "skills",
    routeKeys: ["skills", "skill", "hr_skills"],
    keyField: "skill_code",
    source: "dynamic",
    listQuery: dynamicList("MST_HR_MS_HR_SKILLS",true),
    autoGenerateKey: true,
    buildSave: (form, context) => ({
      parameter: "MST_HR_SKILLS",
      loginid: context.loginid,
      val1s1: context.companyCode,
      val1s2: text(form, "skill_code"),
      val1s3: text(form, "skill_desc"),
      val1s4: text(form, "skill_short_desc"),
      val1s5: text(form, "skill_category"),
      val1s6: text(form, "remarks"),
      val1s7: text(form, "status", "A"),
    }),
    buildDelete: (row, context) => ({ parameter: "MST_HR_SKILLS_DELETE", loginid: context.loginid, code1: context.companyCode, code2: text(row, "skill_code") }),
    fields: [
      { name: "skill_code", label: "Skill Code", required: true, disabledOnEdit: true, width: 140 },
      { name: "skill_desc", label: "Skill Description", required: true, width: 280 },
      { name: "skill_short_desc", label: "Short Description", width: 170 },
      {
  name: "skill_category",
  label: "Skill Category",
  type: "select",
  required: true,
  options: [
    { label: "Professional", value: "P" },
    { label: "Other", value: "O" },
  ],
  width: 170,
},
      { name: "status", label: "Status", type: "select", options: activeInactive, width: 120 },
      { name: "remarks", label: "Remarks", width: 280 },
    ],
    defaults: { status: "A" },
    deleteMode: "master",
  },
  document_types: {
    title: "Document Type Master",
    subtitle: "Maintain HR document type rules, attachment settings, alerts, and active status.",
    master: "document_types",
    gmEndpoint: "document_types",
    routeKeys: ["document_types", "documenttypes", "doc_types", "doctypes"],
    keyField: "doc_type",
    source: "finance",
    financeSaveEndpoint: "upsertHrDocTypes",
    listQuery: dynamicList("MST_HR_MS_HR_DOCTYPES", true),
    buildSave: (form, context) => ({
      ...form,
      company_code: context.companyCode,
      loginid: context.loginid,
      renewal_period_days: num(form, "renewal_period_days"),
      renewal_chgs: num(form, "renewal_chgs"),
      alert_before: num(form, "alert_before"),
      user_id: context.loginid,
    }),
    buildDelete: (row, context) => ({ parameter: "MST_HR_DEL_DOCTYPES", loginid: context.loginid, code1: context.companyCode, code2: text(row, "doc_type") }),
    fields: [
      {
  name: "doc_type",
  label: "Doc Type",
  disabledOnAdd: true,
  disabledOnEdit: true,
  width: 120,
  helperText: "Doc Type is auto generated. You don't need to enter it."
},
      { name: "doctype_name", label: "Document Name", required: true, width: 280 },
      { name: "doctype_short_desc", label: "Short Description", width: 180 },
      { name: "renewal_period_days", label: "Renewal Days", type: "number", width: 140 },
      { name: "renewal_chgs", label: "Renewal Charges", type: "number", width: 150 },
      { name: "mand_flag", label: "Mandatory", type: "select", options: yesNo, width: 120 },
      { name: "attach_folder", label: "Attach Folder", width: 220 },
      { name: "attach_prefix", label: "Attach Prefix", width: 150 },
      { name: "attach_type", label: "Attach Type", width: 140 },
      { name: "doc_editable", label: "Editable", type: "select", options: yesNo, width: 120 },
      { name: "status_flag", label: "Status", type: "select", options: activeInactive, width: 120 },
      { name: "email_id_for_alerts", label: "Email Alerts", type: "email", table: false },
      { name: "alert_before", label: "Alert Before Days", type: "number", table: false },
      { name: "doc_notes", label: "Notes", table: false },
    ],
    defaults: { mand_flag: "N", doc_editable: "Y", status_flag: "A" },
    deleteMode: "master",
  },
  categorymaster: {
    title: "Category Master",
    subtitle: "Maintain employee category codes, short names, remarks, and active status.",
    master: "categorymaster",
    gmEndpoint: "categorymaster",
    routeKeys: ["categorymaster", "category", "appraisal categories"],
    keyField: "category_code",
    source: "dynamic",
   listQuery: dynamicList("MST_HR_MS_HR_CATEGORY",true),
   autoGenerateKey: true,
    buildSave: (form, context) => ({
      parameter: "MST_HR_CATEGORY",  //ins_upd_category
      loginid: context.loginid,
      val1s1: context.companyCode,
      val1s2: text(form, "category_code"),
      val1s3: text(form, "category_name"),
      val1s4: text(form, "category_short_name"),
      val1s5: text(form, "remarks"),
      val1s6: text(form, "status", "A"),
    }),
    buildDelete: (row, context) => ({ parameter: "MST_HR_DEL_CATEGORY", loginid: context.loginid, code1: context.companyCode, code2: text(row, "category_code") }),
    fields: [
      { name: "category_code", label: "Category Code", required: true, disabledOnEdit: true, width: 160 },
      { name: "category_name", label: "Category Name", required: true, width: 260 },
      { name: "category_short_name", label: "Short Name", width: 140 },
      { name: "status", label: "Status", type: "select", options: activeInactive, width: 120 },
      { name: "remarks", label: "Remarks", width: 260 },
    ],
    defaults: { status: "A" },
    deleteMode: "master",
  },
  // grademaster: {
  //   title: "Grade Master",
  //   subtitle: "Maintain employee grades, entitlement flags, and benefit limits.",
  //   master: "grade_master",
  //   gmEndpoint: "grade_master",
  //   routeKeys: ["grade_master", "grade master", "grademaster", "grade"],
  //   keyField: "grade_code",
  //   fields: [
  //     { name: "grade_code", label: "Grade Code", required: true, disabledOnEdit: true, width: 140 },
  //     { name: "grade_name", label: "Grade Name", required: true, width: 240 },
  //     { name: "grade_short_name", label: "Short Name", required: true, width: 140 },
  //     { name: "ot_eligibility", label: "OT Eligible", type: "select", options: yesNo, required: true, width: 130 },
  //     { name: "airfare_entitlement", label: "Airfare", type: "number", width: 130 },
  //     { name: "spouse_af_entitlement", label: "Spouse Airfare", type: "number", width: 150 },
  //     { name: "dep_af_entitlement", label: "Dependent Airfare", type: "number", width: 165 },
  //     { name: "medical_entitlement", label: "Medical", type: "number", width: 130 },
  //     { name: "grade_status", label: "Grade Status", width: 140 },
  //     { name: "status", label: "Status", type: "select", options: activeInactive, width: 120 },
  //     { name: "remarks", label: "Remarks", table: false },
  //   ],
  //   defaults: { ot_eligibility: "N", status: "A" },
  //   deleteMode: "gm",
  // },
  designation: {
    title: "Designation Master",
    subtitle: "Maintain employee designation codes, descriptions, and status.",
    master: "designation",
    gmEndpoint: "designation",
    routeKeys: ["designation"],
    keyField: "desg_code",
    stripEditKeyOnSave: true, 
    fields: [
      { name: "desg_code", label: "Designation Code", required: true, disabledOnEdit: true, width: 170 },
      { name: "desg_name", label: "Designation Name", required: true, width: 280 },
      { name: "desg_short_name", label: "Short Name", required: true, width: 140 },
      { name: "status", label: "Status", type: "select", options: activeInactive, width: 120 },
      { name: "remarks", label: "Remarks", width: 260 },
    ],
    defaults: { status: "A" },
    deleteMode: "gm",
  },
  formaldesignation: {
    title: "Formal Designation Master",
    subtitle: "Maintain labour/formal designation codes used on HR documents.",
    master: "formaldesignation",
    gmEndpoint: "formaldesignation",
    routeKeys: ["formaldesignation", "formal_designation", "labour_designation"],
    keyField: "labour_desg_code",
    fields: [
      { name: "labour_desg_code", label: "Formal Code", required: true, disabledOnEdit: true, width: 150 },
      { name: "labour_desg_name", label: "Formal Designation", required: true, width: 280 },
      { name: "labour_desg_short_name", label: "Short Name", required: true, width: 140 },
      { name: "status", label: "Status", type: "select", options: activeInactive, width: 120 },
      { name: "remarks", label: "Remarks", width: 260 },
    ],
    defaults: { status: "A" },
    deleteMode: "gm",
  },
  leavetype: {
    title: "Leave Type Master",
    subtitle: "Maintain leave type codes, carry-forward behavior, and half-day eligibility.",
    master: "leavetype",
    gmEndpoint: "leavetype",
    routeKeys: ["leavetype", "leave_type"],
    keyField: "leave_type",
    fields: [
      { name: "leave_type", label: "Leave Type", required: true, disabledOnEdit: true, width: 150 },
      { name: "leave_type_desc", label: "Leave Description", required: true, width: 280 },
      { name: "carry_forward", label: "Carry Forward", type: "select", options: yesNo, width: 150 },
      { name: "half_day", label: "Half Day", type: "select", options: yesNo, width: 130 },
    ],
    defaults: { carry_forward: "N", half_day: "N" },
    deleteMode: "master",
  },
  paycomponent: {
    title: "Pay Component Master",
    subtitle: "Maintain salary component codes and descriptions.",
    master: "paycomponent",
    gmEndpoint: "paycomponent",
    routeKeys: ["paycomponent", "pay_component", "hrpaycomponent"],
    keyField: "pay_comp_id",
    fields: [
      { name: "pay_comp_id", label: "Component ID", required: true, disabledOnEdit: true, width: 160 },
      { name: "pay_comp_desc", label: "Component Description", required: true, width: 300 },
      { name: "remarks", label: "Remarks", width: 280 },
    ],
  },
  section: {
    title: "Section Master",
    subtitle: "Maintain HR sections with division, department, head, contact and account details.",
    master: "section",
    gmEndpoint: "section",
    routeKeys: ["section"],
    keyField: "section_code",
    fields: [
      { name: "section_code", label: "Section Code", required: true, disabledOnEdit: true, width: 150 },
      { name: "section_name", label: "Section Name", required: true, width: 260 },
      { name: "section_short_name", label: "Short Name", width: 140 },
      { name: "div_code", label: "Division Code", required: true,  width: 130 },
      { name: "dept_code", label: "Department Code", required: true, width: 140 },
      { name: "sect_head_id", label: "Section Head",width: 150 },
      { name: "phone", label: "Phone", width: 140 },
      { name: "email", label: "Email", type: "email", width: 220 },
      { name: "status", label: "Status", type: "select", options: yesNo, width: 120 },
      { name: "remarks", label: "Remarks", table: false },
      { name: "sect_addr1", label: "Address 1", required: true, table: false },
      { name: "sect_addr2", label: "Address 2", table: false },
      { name: "sect_addr3", label: "Address 3", table: false },
      { name: "staff_cntrl_ac_group", label: "Staff Control A/C Group", table: false },
      { name: "staff_loan_ac_group", label: "Staff Loan A/C Group", table: false },
      { name: "salary_expense_ac_code", label: "Salary Expense A/C", table: false },
      { name: "expense_type", label: "Expense Type", table: false },
      { name: "expense_sub_type", label: "Expense Sub Type", table: false },
    ],
    defaults: { status: "Y" },
    deleteMode: "gm",
  },
  kpiname: {
    title: "KPI Name Master",
    subtitle: "Maintain KPI display names and ordering used by HR KPI setup.",
    master: "kpiname",
    gmEndpoint: "kpiname",
    routeKeys: ["kpiname", "kpi_name"],
    keyField: "kpi_name",
    fields: [
      { name: "kpi_name", label: "KPI Name", required: true, disabledOnEdit: true, width: 280 },
      { name: "serial_no", label: "Serial No", type: "number", required: true, width: 130 },
    ],
    deleteMode: "master",
  },
  kpioperation: {
    title: "Operation Master",
    subtitle: "Maintain KPI operation names and ordering.",
    master: "kpioperation",
    gmEndpoint: "kpioperation",
    routeKeys: ["kpioperation", "operation"],
    keyField: "operation_name",
    fields: [
      { name: "operation_name", label: "Operation Name", required: true, disabledOnEdit: true, width: 320 },
      { name: "serial_no", label: "Serial No", type: "number", required: true, width: 130 },
    ],
    deleteMode: "master",
  },
};








