import { Response } from "express";
import constants from "../../helpers/constants";
import { RequestWithUser } from "../../interfaces/common.interface";
import { IUser } from "../../interfaces/user.interface";
import { groupSchema } from "../../validation/wms/gm.validation";
import { GroupService } from "../../services/WMS/group.service";

export const createGroup = async (req: RequestWithUser, res: Response) => {
  try {
    const requestUser: IUser = req.user;

    const { error } = groupSchema(req.body);
    if (error) {
      res
        .status(constants.STATUS_CODES.BAD_REQUEST)
        .json({ success: false, message: error.message });
      return;
    }
    const {
      company_code,
      prin_code,
      group_name,
      pref_site,
      pref_loc_from,
      pref_loc_to,
      pref_aisle_from,
      pref_aisle_to,
      pref_col_from,
      pref_col_to,
      pref_ht_from,
      pref_ht_to,
      expiry_cons_days,
    } = req.body;

    // Create new group using service (group_code will be generated by DB trigger)
    const createGroup = await GroupService.createGroup({
      prinCode: prin_code,
      companyCode: company_code,
      groupName: group_name,
      prefSite: pref_site,
      prefLocFrom: pref_loc_from,
      prefLocTo: pref_loc_to,
      prefAisleFrom: pref_aisle_from,
      prefAisleTo: pref_aisle_to,
      prefColFrom: pref_col_from,
      prefColTo: pref_col_to,
      prefHtFrom: pref_ht_from,
      prefHtTo: pref_ht_to,
      expiryConsDays: expiry_cons_days,
      createdBy: requestUser.loginid,
      updatedBy: requestUser.loginid,
    } as any);

    if (!createGroup) {
      res
        .status(constants.STATUS_CODES.INTERNAL_SERVER_ERROR)
        .json({ success: false, message: "Error while creating group" });
      return;
    }
    res.status(constants.STATUS_CODES.OK).json({
      success: true,
      message: constants.MESSAGES.GROUP_WMS.GROUP_CREATED_SUCCESSFULLY,
    });
    return;
  } catch (error: any) {
    res
      .status(constants.STATUS_CODES.BAD_REQUEST)
      .json({ success: false, message: error.message });
    return;
  }
};

export const updateGroup = async (req: RequestWithUser, res: Response) => {
  try {
    const requestUser: IUser = req.user;

    const { error } = groupSchema(req.body);
    if (error) {
      res
        .status(constants.STATUS_CODES.BAD_REQUEST)
        .json({ success: false, message: error.message });
      return;
    } const {
      group_code,
      company_code,
      prin_code,
      group_name,
      pref_site,           // This was missing
      pref_loc_from,       // This was missing
      pref_loc_to,         // This was missing
      pref_aisle_from,     // This was missing
      pref_aisle_to,       // This was missing
      pref_col_from,       // This was missing
      pref_col_to,         // This was missing
      pref_ht_from,        // This was missing
      pref_ht_to,          // This was missing
      expiry_cons_days,    // This was missing
    } = req.body;

    // Check if group exists
    const groupExists = await GroupService.findByGroupCodeAndCompany(
      group_code,
      prin_code,
      company_code
    );

    if (!groupExists) {
      res.status(constants.STATUS_CODES.BAD_REQUEST).json({
        success: false,
        message: constants.MESSAGES.GROUP_WMS.GROUP_DOES_NOT_EXISTS,
      });
      return;
    }

    // Update group using service
    const updateSuccess = await GroupService.updateGroup(
      group_code,
      prin_code,
      company_code,
      {
        groupName: group_name,
        prefSite: pref_site,
        prefLocFrom: pref_loc_from,
        prefLocTo: pref_loc_to,
        prefAisleFrom: pref_aisle_from,
        prefAisleTo: pref_aisle_to,
        prefColFrom: pref_col_from,
        prefColTo: pref_col_to,
        prefHtFrom: pref_ht_from,
        prefHtTo: pref_ht_to,
        expiryConsDays: expiry_cons_days,
        updatedBy: requestUser.loginid,
      }
    );

    if (!updateSuccess) {
      res
        .status(constants.STATUS_CODES.INTERNAL_SERVER_ERROR)
        .json({ success: false, message: "Error while updating group" });
      return;
    }
    res.status(constants.STATUS_CODES.OK).json({
      success: true,
      message: constants.MESSAGES.GROUP_WMS.GROUP_UPDATED_SUCCESSFULLY,
    });
    return;
  } catch (error: any) {
    res
      .status(constants.STATUS_CODES.BAD_REQUEST)
      .json({ success: false, message: error.message });
    return;
  }
};

  export const deleteGroups = async (req: RequestWithUser, res: Response) => {
    try {
      const groupsToDelete = req.body;

      console.log('=== DELETE GROUPS REQUEST ===');
      console.log('Full request body:', JSON.stringify(groupsToDelete, null, 2));

      if (!Array.isArray(groupsToDelete) || !groupsToDelete.length) {
        console.log('Error: No groups to delete or invalid format');
        res.status(constants.STATUS_CODES.BAD_REQUEST).json({
          success: false,
          message: constants.MESSAGES.GROUP_WMS.SELECT_AT_LEAST_ONE_GROUP,
        });
        return;
      }

      // Validate each item
      const invalidItems = groupsToDelete.filter(item => 
        !item.group_code || !item.prin_code || !item.company_code
      );
      
      if (invalidItems.length > 0) {
        console.log('Error: Invalid items found', invalidItems);
        res.status(constants.STATUS_CODES.BAD_REQUEST).json({
          success: false,
          message: "Invalid data: missing group_code, prin_code, or company_code",
        });
        return;
      }

      // Group items by (prin_code, company_code) pair
      const groupedByPrinAndCompany: { [key: string]: any[] } = {};
      
      groupsToDelete.forEach(item => {
        const key = `${item.prin_code}_${item.company_code}`;
        if (!groupedByPrinAndCompany[key]) {
          groupedByPrinAndCompany[key] = [];
        }
        groupedByPrinAndCompany[key].push(item);
      });

      console.log('Grouped by prin_code and company_code:', groupedByPrinAndCompany);

      let totalDeleted = 0;
      let totalFailed = 0;
      const deleteResults = [];

      // Delete groups for each (prin_code, company_code) combination
      for (const [key, items] of Object.entries(groupedByPrinAndCompany)) {
        const [prinCode, companyCode] = key.split('_');
        const groupCodes = items.map(item => item.group_code);

        console.log(`Deleting groups for prin_code=${prinCode}, company_code=${companyCode}:`, groupCodes);

        try {
          const deleteSuccess = await GroupService.deleteGroups(
            groupCodes,
            prinCode,
            companyCode
          );

          if (deleteSuccess) {
            const deletedCount = groupCodes.length;
            totalDeleted += deletedCount;
            deleteResults.push({
              prin_code: prinCode,
              company_code: companyCode,
              success: true,
              deleted: deletedCount,
              groups: groupCodes
            });
            console.log(`Successfully deleted ${deletedCount} groups for ${prinCode}/${companyCode}`);
          } else {
            totalFailed += groupCodes.length;
            deleteResults.push({
              prin_code: prinCode,
              company_code: companyCode,
              success: false,
              message: "No groups were deleted",
              groups: groupCodes
            });
            console.log(`Failed to delete groups for ${prinCode}/${companyCode}`);
          }
        } catch (error: any) {
          totalFailed += groupCodes.length;
          deleteResults.push({
            prin_code: prinCode,
            company_code: companyCode,
            success: false,
            message: error.message,
            groups: groupCodes
          });
          console.error(`Error deleting groups for ${prinCode}/${companyCode}:`, error.message);
        }
      }

      console.log('Delete summary:', {
        totalAttempted: groupsToDelete.length,
        totalDeleted,
        totalFailed,
        results: deleteResults
      });

      if (totalDeleted === 0) {
        console.log('Error: No groups were deleted');
        res.status(constants.STATUS_CODES.BAD_REQUEST).json({
          success: false,
          message: "Failed to delete any groups. No records were deleted.",
          results: deleteResults
        });
        return;
      }

      let message = constants.MESSAGES.GROUP_WMS.GROUP_DELETED_SUCCESSFULLY;
      if (totalFailed > 0) {
        message = `Successfully deleted ${totalDeleted} group(s). ${totalFailed} group(s) could not be deleted.`;
      }

      console.log('Delete successful!');
      res.status(constants.STATUS_CODES.OK).json({
        success: true,
        message: message,
        data: {
          totalDeleted,
          totalFailed,
          results: deleteResults
        }
      });
      return;
    } catch (error: any) {
      console.error('=== DELETE ERROR ===');
      console.error('Error message:', error.message);
      console.error('Error stack:', error.stack);
      console.error('Full error:', error);
      
      res
        .status(constants.STATUS_CODES.INTERNAL_SERVER_ERROR)
        .json({ success: false, message: `Error occurred while deleting data: ${error.message}` });
      return;
    }
  };
   