export type GrnReportT = {
  company_code: string;
  company_name: string;
  prin_code: string;
  prin_name: string;
  job_no: string;
  txn_date: Date;
  prod_code: string;
  prod_name: string;
  uppp: number;
  site_code: string;
  p_uom: string;
  l_uom: string;
  vessel_name: string;
  container_no: string;
  seal_no: string;
  po_no: string;
  doc_ref: string;
  lot_no: string;
  mfg_date: Date;
  exp_date: Date;
  grn_no: number;
  grn_date: Date;
  user_id: string;
  volume: number;
  receipt_date: Date;
  container_size: number;
  origin_country: string;
  site_ind: string;
  batch_no: string;
  unstuff_date: string;
  job_class: string;
  s_no: number;
  seal_no1: string;
  cnt_lotno: number;
  prin_ref2: string;
  products: TProductData[];
};
type TProductData = {
  adj_number: number;
  isTotal: boolean;
  stockTotal: boolean;
  app_key_number: string;
  applied_keyno: string;
  batch_no: string | null;
  bl_no: string | null;
  closing_balance: string;
  company_code: string;
  curr_code: string;
  cust_code: string | null;
  da_no: number;
  dn_no: string;
  ex_rate: string;
  exitbill1: string | null;
  exitbill2: string | null;
  exp_container_no: string | null;
  exp_container_sealno: string | null;
  exp_container_size: string | null;
  exp_container_type: string | null;
  container_no: string;
  exp_date: string | null;
  grosswt: string;
  gross_wt1: string | null;
  harm_code: string;
  hs_code: string;
  identity_number: number;
  jobtran_luom: string;
  jobtran_puom: string;
  key_number: string;
  l_uom: string;
  location_code: string;
  lot_no: string | null;
  lqty_cl_balance: string;
  lqty_op_balance: number;
  manu_code: string;
  mfg_date: string | null;
  model_no: string;
  netwt: string;
  opening_balance: number;
  order_no: string | null;
  order_srno: string | null;
  origin_country: string;
  p_uom: string;
  pack_key: string | null;
  pallet_id: string | null;
  pallet_serial_no: string | null;
  pqty_cl_balance: string;
  pqty_op_balance: number;
  prin_code: string;
  prin_ref1: string | null;
  prin_stat: string | null;
  prod_bredth: string;
  prod_code: string;
  prod_grade1: string | null;
  prod_grade2: string | null;
  prod_height: string;
  prod_length: string;
  prod_name: string;
  qty_expected: string;
  receipt_date: string;
  receipt_type: string;
  seal_no: string | null;
  sign_indicator: number;
  site_code: string;
  site_ind: string;
  site_type: string | null;
  stn_number: string;
  t_gross_wt: string;
  t_net_wt: string;
  txn_date: string;
  unit_price: string;
  uppp: number;
  user_dt: string;
  vessel_name: string;
  grnTotal: boolean;
  volume: string;
  group_name: string;
  qtypuom: number;
  qtyluom: number;
  qty: number;
  job_qtyexpected: number;
  job_no_of_cse: number;
  job_qtyluom_expected: number;
  job_qtypuom_expected: number;
  no_of_cse: number;
  qtypuom_expected: number;
  qtyluom_expected: number;
  qtyexpected: number;
  qty_rcvd: number;
  qtypuom_dam: number;
  qtyluom_dam: number;
  qty_dam: number;
  cnt_lotno: number;
  children: TGrnProductChildren[];
};

export type TGrnProductChildren = {
  serial_number?: string;
  packdet_no?: string;
};
