export type IJobInbListingView = {
  company_code: string;
  prin_code: string;
  prin_name: string;
  job_class: string;
  job_date: Date;
  order_type: string;
  confirm_date: Date;
  job_no: string;
  doc_ref: string;
  canceled: string;
  cancel_date: Date;
  invoiced: string;
  invoice_date: Date;
  created_at?: Date;
  created_by: string;
  updated_at?: Date;
  updated_by: string;
};
export type TJobInboundWms = {
  // prin_name: string;
  company_code?: string;
  prin_code: string;
  job_no: string;
  job_date: Date;
  job_type: string;
  job_class: string;
  dept_code: string;
  transport_mode: string;
  doc_ref: string;
  port_code: string;
  description1: string;
  description2: string;
  prin_ref1: string;
  prin_ref2: string;
  remarks: string;
  eta?: Date;
  ata?: Date;
  etd?: Date;
  schedule_date?: Date;
  payment_terms: string;
  curr_code: string;
  ex_rate: number;
  frieght_value: number;
  insurance_value: number;
  cust_code: string;
  container_flag: string;
  container: string;
  packdet: string;
  // prin_name: string;
  allocated: string;

  canceled: string;

  confirmed: string;

  grn_no: number;

  invoiced: string;

  completed: string;
  exp_jobno: string;
  picked: string;
  ordered: string;
  destination_port: string;
  vessel_name: string;
  voyage_no: string;
  payableat: string;
  place_receipt: string;
  place_delivery: string;
  no_of_original_bl: number;
  broker_code: string;
  quotation_ref: string;

  be_deposits: string;
  ind_freight: string;
  country_origin: string;
  country_destination: string;

  custom_recno: string;
  doc_ref2: string;
  hawb: string;
  reexport: string;
  ref_jobno: string;
  combined_jobno: string;
  carrier: string;
  job_lock: string;
  courier_code: string;
  delivery_point: string;
  div_code: string;
  salesman_code: string;
  transit_time: string;
  document_check: string;
  delivery_remarks: string;
  cargo_received: string;
  delivered_by: string;
  canceled_by: string;
  cancel_remarks: string;
  send_mail: string;
  backlog_mail: string;
  dplan_flag: string;
  trans_batch_id: string;
  send_mail_dn: string;
  kpi_inc: string;
  kpi_exc_remark: string;
  job_category: string;
  edit_user: string;
  tx_cat_code: string;
  bcf_code: string;
  request_category: string;
  load_point: string;
  created_at?: Date;
  created_by: string;
  updated_at?: Date;
  updated_by: string;
  job_classification?: string;
};

export type TJobInboundWmsWithPrinName = {
  prin_name: string;
  company_code?: string;
  prin_code: string;
  job_no: string;
  job_date: Date;
  job_type: string;
  job_class: string;
  dept_code: string;
  transport_mode: string;
  doc_ref: string;
  port_code: string;
  description1: string;
  description2: string;
  prin_ref1: string;
  prin_ref2: string;
  remarks: string;
  eta?: Date;
  ata?: Date;
  etd?: Date;
  schedule_date?: Date;
  payment_terms: string;
  curr_code: string;
  ex_rate: number;
  frieght_value: number;
  insurance_value: number;
  cust_code: string;
  container_flag: string;
  container: string;
  packdet: string;
  // prin_name: string;
  allocated: string;

  canceled: string;

  confirmed: string;

  grn_no: number;

  invoiced: string;

  completed: string;
  exp_jobno: string;
  picked: string;
  ordered: string;
  destination_port: string;
  vessel_name: string;
  voyage_no: string;
  payableat: string;
  place_receipt: string;
  place_delivery: string;
  no_of_original_bl: number;
  broker_code: string;
  quotation_ref: string;

  be_deposits: string;
  ind_freight: string;
  country_origin: string;
  country_destination: string;

  custom_recno: string;
  doc_ref2: string;
  hawb: string;
  reexport: string;
  ref_jobno: string;
  combined_jobno: string;
  carrier: string;
  job_lock: string;
  courier_code: string;
  delivery_point: string;
  div_code: string;
  salesman_code: string;
  transit_time: string;
  document_check: string;
  delivery_remarks: string;
  cargo_received: string;
  delivered_by: string;
  canceled_by: string;
  cancel_remarks: string;
  send_mail: string;
  backlog_mail: string;
  dplan_flag: string;
  trans_batch_id: string;
  send_mail_dn: string;
  kpi_inc: string;
  kpi_exc_remark: string;
  job_category: string;
  edit_user: string;
  tx_cat_code: string;
  bcf_code: string;
  request_category: string;
  load_point: string;
  created_at?: Date;
  created_by: string;
  updated_at?: Date;
  updated_by: string;
};

export type TTransactionJobDetail = {
  company_code: string;
  doc_type: string;
  doc_no: number;
  serial_no: number;
  dtl_sr_no: number;
  doc_date: Date;
  ac_code: string;
  job_no: string;
  doc_refno: string;
  doc_refno_2: string;
  amount: number;
  sign_ind: number;
  lcur_amount: number;
  curr_code: string;
  ex_rate: number;
  div_code: string;
};
export type TTransactionExpenseDetail = {
  ExpenseType: { exp_description: string };
  ExpenseSubType: { exp_subtype_description: string };
  exp_description?: string;
  exp_subtype_description?: string;
  company_code: string;
  doc_type: string;
  doc_no: number;
  serial_no: number;
  dtl_sr_no: number;
  doc_date: Date;
  ac_code: string;
  exp_type_code: string;
  exp_subtype_code: string;
  exp_code: string;
  amount: number;
  sign_ind: number;
  lcur_amount: number;
  curr_code: string;
  ex_rate: number;
  div_code: string;
  job_no: string;
};
