
export interface TPutawaymanual {
  COMPANY_CODE: string;
  PRIN_CODE: string;
  JOB_NO: string;
  TXN_TYPE: string;
  TXN_DATE: string | Date;

  PACKDET_NO?: number; // generated by trigger
  KEY_NUMBER?: string;

  PROD_CODE: string;
  SITE_CODE: string;
  LOCATION_CODE?: string;

  QUANTITY: number;
  QTY_PUOM: number;
  QTY_LUOM: number;
  P_UOM: string;
  L_UOM?: string;

  QTY_CONFIRMED?: number;
  PQTY_CONFIRMED?: number;
  LQTY_CONFIRMED?: number;
  PUOM_CONFIRMED?: string;
  LUOM_CONFIRMED?: string;

  UPPP?: number;
  PACK_KEY?: string;
  UPP?: number;
  CONFIRM_DATE?: string | Date;

  CUST_CODE?: string;
  ORDER_NO?: string;
  ORDER_SRNO?: number;
  VESSEL_NAME?: string;
  CONTAINER_NO?: string;
  SEAL_NO?: string;
  PO_NO?: string;
  BL_NO?: string;
  DOC_REF?: string;
  LOT_NO?: string;
  PALLET_ID?: string;
  PALLET_SERIAL_NO?: string;
  MANU_CODE?: string;

  MFG_DATE?: string | Date;
  EXP_DATE?: string | Date;

  CURR_CODE?: string;
  EX_RATE?: number;
  UNIT_PRICE?: number;

  SELECTED?: string;   // default 'N'
  ALLOCATED?: string;  // default 'N'
  CONFIRMED?: string;  // default 'N'

  IDENTITY_NUMBER: number;

  USER_ID?: string;
  USER_DT?: string | Date;
  APPLIED_KEYNO?: string;
  RECEIPT_TYPE?: string;
  RECEIPT_DATE?: string | Date;

  CONTAINER_SIZE?: number;
  MOC1?: string;
  MOC2?: string;
  ORIGIN_COUNTRY?: string;
  SHELF_LIFE_DAYS?: number;
  SHELF_LIFE_DATE?: string | Date;
  TASK_ORDER?: number;

  PROD_ATTRIB_CODE?: string;
  PROD_GRADE1?: string;
  PROD_GRADE2?: string;
  TX_IDENTITY_NUMBER?: string;
  ASSIGNED_PDA_USER?: string;
  PDA_VERIFIED?: string;
  SUPP_CODE?: string;
  PUTAWAY_DT?: string | Date;

  MASTER_CTN?: number;
  LOOSE_CTN?: number;
  HS_CODE?: string;

  NET_WT?: number;
  NET_VOLUME?: number;
  LC_PO_VALUE?: number;
  GROSS_WT?: number;
  DA_NO?: number;

  BATCH_NO?: string;
  EDIT_USER?: string;
  CARTON_NO?: string;

  created_at?: string | Date;
  created_by?: string;
  updated_at?: string | Date;
  updated_by?: string;
}
