import { Save, X } from "lucide-react";
import { FormEvent, useState } from "react";
import { executeDynamicMutation, getDynamicLookup, LookupRow } from "../../api/lookups";
import { AutoDismissAlert } from "../../components/ui/AutoDismissAlert";
import { Button } from "../../components/ui/Button";
import { Card, CardContent, CardHeader } from "../../components/ui/Card";
import { Input } from "../../components/ui/Input";
import { LookupField } from "../../components/ui/LookupField";
import { useAuth } from "../../state/AuthContext";

const Account_AC_CODE_Serach = "Account_AC_CODE_Serach";

// Matches the WHEN branch added to PROC_BUILD_DYNAMIC_INS_UPD_PURCHASE_SALE:
//   P_VAL1S1 : EXPENSE_CODE  (blank on insert -> autogenerated in Oracle)
//   P_VAL1S2 : COMPANY_CODE
//   P_VAL1S3 : EXPENSE_NAME
//   P_VAL1S4 : AC_CODE
//   P_VAL1S5 : USER_ID
//   P_VAL1D1 : USER_DT
const PURCHASE_SALE_MSE_EXPENSES = "PURCHASE_SALE_MSE_EXPENSES";

export type TExpenseMaster = {
  expense_code?: string;
  expense_name?: string;
  ac_code?: string;
  ac_name?: string;
  user_id?: string;
  user_dt?: string;
  date1?: string | null;
};

type FormMode = "add" | "edit" | "view";

type Props = {
  mode: FormMode;
  existingData?: Partial<TExpenseMaster>;
  onClose: (shouldRefetch?: boolean) => void;
};

const EMPTY: TExpenseMaster = {
  expense_code: "",
  expense_name: "",
  ac_code: "",
  ac_name: "",
  user_id: "",
  user_dt: "",
};

// Same A/C Code lookup columns used by the Asset Sale / Disposal register,
// so the picker shows Code + Name side by side.
const accountColumns = [
  { field: "ac_code", header: "A/C Code" },
  { field: "ac_name", header: "A/C Name" },
];

export function AddExpenseMasterForm({ mode, existingData, onClose }: Props) {
  const { user } = useAuth();
  const readonly = mode === "view";
  const isEdit = mode === "edit";
  const companyCode = user?.company_code ?? "";

  const [form, setForm] = useState<TExpenseMaster>(() => ({ ...EMPTY, ...existingData }));
  const [errors, setErrors] = useState<Partial<Record<keyof TExpenseMaster, string>>>({});
  const [saving, setSaving] = useState(false);
  const [apiError, setApiError] = useState("");

  const setField = (field: keyof TExpenseMaster, value: string) =>
    setForm((prev) => ({ ...prev, [field]: value }));

  // ── Validation ──────────────────────────────────────────────────────────
  // expense_code is autogenerated by the backend (see Doc No field below),
  // so it's never validated or sent as required input here — only
  // expense_name and (optionally) the A/C mapping matter on this form.
  const validate = (): boolean => {
    const next: Partial<Record<keyof TExpenseMaster, string>> = {};
    if (!form.expense_name?.trim()) next.expense_name = "Expense Name is required";
    setErrors(next);
    return Object.keys(next).length === 0;
  };

  // ── Submit ──────────────────────────────────────────────────────────────
  // Calls PURCHASE_SALE_MSE_EXPENSES directly — the generic dynamic
  // insert/update dispatcher (PROC_BUILD_DYNAMIC_INS_UPD_PURCHASE_SALE on
  // the Oracle side). Positional P_VAL1S* / P_VAL1D* params map to the
  // columns as documented above; EXPENSE_CODE is left blank on create so
  // the procedure autogenerates it, and passed through unchanged on edit.
  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault();
    if (readonly) return;
    if (!validate()) return;

    setSaving(true);
    setApiError("");
    try {
      await executeDynamicMutation({
        parameter: PURCHASE_SALE_MSE_EXPENSES,
        loginid: user?.loginid ?? "ADMIN",
        val1s1: isEdit ? form.expense_code ?? "" : "",
        val1s2: companyCode,
        val1s3: form.expense_name?.trim() ?? "",
        val1s4: form.ac_code ?? "",
        val1s5: user?.loginid ?? "ADMIN",
        // val1d1: new Date().toISOString(),
      });

      onClose(true);
    } catch (error) {
      setApiError(error instanceof Error ? error.message : "Unable to save expense master record");
    } finally {
      setSaving(false);
    }
  };

  // ── UI ──────────────────────────────────────────────────────────────────
  return (
    <div className="flex min-h-[420px] flex-col">
      <form className="grid flex-1 content-start gap-4 overflow-auto p-4" id="expense-master-form" onSubmit={handleSubmit}>
        <AutoDismissAlert notice={apiError ? { type: "error", message: apiError } : null} onClose={() => setApiError("")} />

        <Card>
          <CardHeader>
            <div>
              <p className="eyebrow">Expense</p>
              <h2 className="m-0 text-sm font-semibold">Basic Information</h2>
            </div>
          </CardHeader>
          <CardContent className="grid grid-cols-1 gap-x-4 gap-y-4 md:grid-cols-2">
            <label className="field">
              <span>Expense Code</span>
              <Input disabled value={form.expense_code || "Autogenerated"} />
            </label>

            <label className="field">
              <span>
                Expense Name <strong className="text-destructive">*</strong>
              </span>
              <Input
                disabled={readonly}
                value={form.expense_name ?? ""}
                onChange={(e) => setField("expense_name", e.target.value)}
                placeholder="e.g. Office Supplies"
              />
              {errors.expense_name && (
                <span className="text-destructive text-xs mt-0.5">{errors.expense_name}</span>
              )}
            </label>

            <div className="md:col-span-2">
              <Lookup
                label="A/C Code"
                parameter={Account_AC_CODE_Serach}
                value={form.ac_code ?? ""}
                displayValue={
                  form.ac_code && form.ac_name ? `${form.ac_code} - ${form.ac_name}` : form.ac_code ?? ""
                }
                valueField="ac_code"
                displayFields={["ac_code", "ac_name"]}
                columns={accountColumns}
                companyCode={companyCode}
                disabled={readonly}
                onSelect={(value, row) => {
                  setField("ac_code", value);
                  if (row) setField("ac_name", String(row.ac_name ?? ""));
                }}
              />
            </div>
          </CardContent>
        </Card>
      </form>

      <div className="flex items-center justify-end gap-2 border-t bg-card p-4">
        <Button variant="outline" onClick={() => onClose(false)}>
          <X size={15} /> {readonly ? "Close" : "Cancel"}
        </Button>
        {!readonly && (
          <Button disabled={saving} type="submit" form="expense-master-form">
            {saving ? <span className="spinner small" /> : <Save size={15} />} {saving ? "Saving..." : isEdit ? "Update" : "Submit"}
          </Button>
        )}
      </div>
    </div>
  );
}

// Thin wrapper around LookupField, matching the pattern used by
// AssetSaleRegisterPage's Lookup helper — fetches the option list from a
// dynamic-lookup parameter and shows Code/Name columns in the picker.
function Lookup({
  label,
  parameter,
  value,
  displayValue,
  valueField,
  displayFields,
  columns,
  companyCode,
  disabled,
  onSelect,
}: {
  label: string;
  parameter: string;
  value: string;
  displayValue: string;
  valueField: string;
  displayFields: string[];
  columns: { field: string; header: string }[];
  companyCode: string;
  disabled?: boolean;
  onSelect: (value: string, row: LookupRow | null) => void;
}) {
  return (
    <LookupField
      label={label}
      value={value}
      displayValue={displayValue}
      columns={columns}
      valueField={valueField}
      displayFields={displayFields}
      disabled={disabled}
      loadOptions={() =>
        getDynamicLookup({
          parameter,
          code1: companyCode,
          code2: "",
          code3: "",
          code4: "",
          number1: 0,
          number2: 0,
          number3: 0,
          number4: 0,
          date1: null,
          date2: null,
          date3: null,
          date4: null,
        })
      }
      onChange={onSelect}
    />
  );
}