import { Save, X } from "lucide-react";
import { FormEvent, useState } from "react";
import { executeDynamicMutation } from "../../api/lookups";
import { AutoDismissAlert } from "../../components/ui/AutoDismissAlert";
import { Button } from "../../components/ui/Button";
import { Card, CardContent, CardHeader } from "../../components/ui/Card";
import { Input } from "../../components/ui/Input";
import { useAuth } from "../../state/AuthContext";

// Matches the WHEN branch in PROC_BUILD_DYNAMIC_INS_UPD_PURCHASE_SALE:
//   P_VAL1S1 : BRAND_CODE   (blank on insert -> autogenerated in Oracle)
//   P_VAL1S2 : COMPANY_CODE
//   P_VAL1S3 : BRAND_NAME
//   P_VAL1S4 : USER_ID
// USER_DT is now stamped server-side with SYSDATE inside the procedure, so
// we deliberately do NOT send val1d1 anymore — sending a client date here
// was the source of the recurring ORA-01861 error.
const PURCHASE_SALE_MSE_PRODBRAND = "PURCHASE_SALE_MSE_PRODBRAND";

export type TProductBrand = {
  brand_code?: string;
  brand_name?: string;
  user_id?: string;
  user_dt?: string;
};

type FormMode = "add" | "edit" | "view";

type Props = {
  mode: FormMode;
  existingData?: Partial<TProductBrand>;
  onClose: (shouldRefetch?: boolean) => void;
};

const EMPTY: TProductBrand = {
  brand_code: "",
  brand_name: "",
  user_id: "",
  user_dt: "",
};

export function AddProductBrandForm({ mode, existingData, onClose }: Props) {
  const { user } = useAuth();
  const readonly = mode === "view";
  const isEdit = mode === "edit";
  const companyCode = user?.company_code ?? "";

  const [form, setForm] = useState<TProductBrand>(() => ({ ...EMPTY, ...existingData }));
  const [errors, setErrors] = useState<Partial<Record<keyof TProductBrand, string>>>({});
  const [saving, setSaving] = useState(false);
  const [apiError, setApiError] = useState("");

  const setField = (field: keyof TProductBrand, value: string) =>
    setForm((prev) => ({ ...prev, [field]: value }));

  // ── Validation ──────────────────────────────────────────────────────────
  // brand_code is autogenerated by the backend (see Doc No field below),
  // so it's never validated or sent as required input here — only
  // brand_name matters on this form.
  const validate = (): boolean => {
    const next: Partial<Record<keyof TProductBrand, string>> = {};
    if (!form.brand_name?.trim()) next.brand_name = "Brand Name is required";
    setErrors(next);
    return Object.keys(next).length === 0;
  };

  // ── Submit ──────────────────────────────────────────────────────────────
  // Calls PURCHASE_SALE_MSE_PRODBRAND directly — the generic dynamic
  // insert/update dispatcher (PROC_BUILD_DYNAMIC_INS_UPD_PURCHASE_SALE on
  // the Oracle side). Positional P_VAL1S* params map to the columns as
  // documented above; BRAND_CODE is left blank on create so the procedure
  // autogenerates it, and passed through unchanged on edit.
  //
  // NOTE: val1d1 is intentionally NOT sent. The procedure now stamps
  // USER_DT with SYSDATE itself, which permanently avoids the ORA-01861
  // ("literal does not match format string") that kept recurring when the
  // backend controller bound a raw ISO date string into an Oracle DATE
  // parameter without converting it to a real JS Date first.
  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault();
    if (readonly) return;
    if (!validate()) return;

    setSaving(true);
    setApiError("");
    try {
      await executeDynamicMutation({
        parameter: PURCHASE_SALE_MSE_PRODBRAND,
        loginid: user?.loginid ?? "ADMIN",
        val1s1: isEdit ? form.brand_code ?? "" : "",
        val1s2: companyCode,
        val1s3: form.brand_name?.trim() ?? "",
        val1s4: user?.loginid ?? "ADMIN",
      });

      onClose(true);
    } catch (error) {
      setApiError(error instanceof Error ? error.message : "Unable to save product brand record");
    } finally {
      setSaving(false);
    }
  };

  // ── UI ──────────────────────────────────────────────────────────────────
  return (
    <div className="flex min-h-[320px] flex-col">
      <form className="grid flex-1 content-start gap-4 overflow-auto p-4" id="brand-master-form" onSubmit={handleSubmit}>
        <AutoDismissAlert notice={apiError ? { type: "error", message: apiError } : null} onClose={() => setApiError("")} />

        <Card>
          <CardHeader>
            <div>
              <p className="eyebrow">Product Brand</p>
              <h2 className="m-0 text-sm font-semibold">Basic Information</h2>
            </div>
          </CardHeader>
          <CardContent className="grid grid-cols-1 gap-x-4 gap-y-4 md:grid-cols-2">
            <label className="field">
              <span>Brand Code</span>
              <Input disabled value={form.brand_code || "Autogenerated"} />
            </label>

            <label className="field">
              <span>
                Brand Name <strong className="text-destructive">*</strong>
              </span>
              <Input
                disabled={readonly}
                value={form.brand_name ?? ""}
                onChange={(e) => setField("brand_name", e.target.value)}
                placeholder="e.g. Samsung"
              />
              {errors.brand_name && (
                <span className="text-destructive text-xs mt-0.5">{errors.brand_name}</span>
              )}
            </label>
          </CardContent>
        </Card>
      </form>

      <div className="flex items-center justify-end gap-2 border-t bg-card p-4">
        <Button variant="outline" onClick={() => onClose(false)}>
          <X size={15} /> {readonly ? "Close" : "Cancel"}
        </Button>
        {!readonly && (
          <Button disabled={saving} type="submit" form="brand-master-form">
            {saving ? <span className="spinner small" /> : <Save size={15} />} {saving ? "Saving..." : isEdit ? "Update" : "Submit"}
          </Button>
        )}
      </div>
    </div>
  );
}