export default {
  MASTER: {
    COUNTRY: [
      "country_code",
      "country_name",
      "country_gcc",
      "company_code",
      "short_desc",
      "nationality",
    ],
    ALERT: [
      "company_code",
      "op_code",
      "op_type",
      "op_desc",
      "op_sequence",
      "op_module",
      "op_mode",
      "instruction",
    ],
    ACTIVITY_KPI: [
      "prin_code",
      "job_type",
      "act_code",
      "cust_code",
      "exp_hours",
      "company_code",
      "updated_at",
      "updated_by",
      "created_by",
      "created_at",
    ],
    PRODUCTTYPE: ["prodtype_code", "prodtype_desc", "company_code"],

    LOCTIONTYPE: [
      "loc_type",
      "loc_cbm",
      "loc_wt",
      "push_level",
      "user_id",
      "user_dt",
      "company_code",
      "loc_name",
    ],

    WAREHOUSE: [
      "company_code",
      "wh_code",
      "wh_name",
      "address",
      "country_code",
      "phone",
      "city",
    ],
    SUPPLIER: [],

    PRINCIPAL: [
      "company_code",
      "prin_code",
      "prin_name",
      "prin_addr1",
      // "prin_addr2",
      // "prin_addr3",
      // "prin_addr4",
      "prin_city",
      // "country_code",
      // "tax_country_code",
      // "tax_country_sn",
      // "territory_code",
      // "sector_code",
      // "prin_email1",
      // "prin_email2",
      // "prin_email3",
      // "prin_telno1",
      // "prin_telno2",
      // "prin_telno3",
      // "prin_faxno1",
      // "prin_faxno2",
      // "prin_faxno3",
      // "prin_ref1",
      "prin_status",
      // "acc_email",
      // "prin_dept_code",
      // "prin_acref",
      // "trn_no",
      // "trn_exp_date",
      // "prin_invdate",
      // "curr_code",
      // "prin_infze",
      // "credit_limit",
      // "creditdays",
      // "creditdays_freight",
      // "prin_lic_no",
      // "prin_lic_type",
      // "comm_reg_no",
      // "comm_exp_date",
      // "prin_imp_code",
      // "parent_prin_code",
      // "files",
      // "pick_wave",
      // "pick_wave_qty_sort",
      // "pick_wave_ign_min_exp",
      // "pref_site",
      // "pref_loc_from",
      // "pref_loc_to",
      // "pref_aisle_from",
      // "pref_aisle_to",
      // "pref_col_from",
      // "pref_col_to",
      // "pref_ht_from",
      // "pref_ht_to",
      // "prin_siteind",
      // "service_date",
      // "storage_type",
      // "default_foc",
      // "under_value",
      // "auto_insert_billactivity",
      // "prin_charge",
      // "prin_pricechk",
      // "prin_landedpr",
      // "auto_job",
      // "validate_lotno",
      // "storage_productwise",
      // "dir_shpmnt",
      // "validate_expdate",
      // "minperiod_exppick",
      // "rcpt_exp_limit",
      // "perpectual_confirm_allow",
      // "automate_activity",
    ],
  },
  TANSACTION: {
    INBOUND: {
      PACKING_DETAIL: [
        "company_code",
        "prin_code",
        "job_no",
        "prod_code",
        "prod_name",
        "qty_puom",
        "p_uom",
        "qty_luom",
        "l_uom",
        "quantity",
        "container_no",
      ],
      TALLY_DETAIL: [
        "company_code",
        "prin_code",
        "job_no",
        "container_no",
        "prod_code",
        "prod_attrib_code",
        "quantity",
        "pda_quantity",
        "location_code",
        "barcode",
        "size_value",
        "seq_number",
        "user_id",
        "user_dt",
        "packdet_no",
        "carton_no",
        "batch_no",
        "prod_exp_date",
        "pallet_id",
        "selected",
        "allocated",
        "pda_qty_puom",
        "pda_puom",
        "pda_qty_luom",
        "pda_luom",
        "lot_no",
        "prod_mfg_date",
        "site_ind",
        "tally_processed",
        "putaway_processed",
        "target_location",
        "receipt_type",
        "vessel_name",
        "exp_date",
        "mfg_date",
        "uppp",
        "origin_country",
        "batch_id",
        "carton_tally",
        "putaway_pda_processed",
        "prod_exp_char",
        "prod_mfg_char",
      ],
      SHIPMENT_DETAIL: [
        "company_code",
        "prin_code",
        "job_no",
        "vessel_name",
        "voyage_no",
        "container_no",
        "seal_no",
        "container_size",
        "container_type",
        "bl_no",
        "packdet_entered",
        "user_id",
        "user_dt",
        "moc1",
        "moc2",
        "act_code",
        "uoc",
        "volume",
        "net_weight",
        "assigned_pda_user",
        "po_no",
        "sr_comp_code",
        "sr_cust_code",
        "supp_code",
        "assigned_tally_user",
        "unstuff_start",
        "unstuff_end",
        "tally_start_time",
        "tally_end_time",
        "putaway_start_time",
        "putaway_end_time",
        "old_container_no",
        "old_vessel_name",
        "old_voyage_no",
        "sr_reason_code",
        "promo_shift",
        "hbl_no",
        "asn_no",
        "doc_ref_no",
        "cust_decl_no",
        "truck_no",
      ],
      PUTWAY_DETAIL: [
        "packdet_no",
        "prod_code",
        "qty_puom",
        "p_uom",
        "qty_luom",
        "l_uom",
        "quantity",
        "l_uom",
        "serial_no",
        "batch_no",
        "lot_no",
        "mfg_date",
        "exp_date",
        "container_no",
        "po_no",
        "bl_no",
      ],
    },
    OUTOUND: {
      PICKING_DETAILS: [
        "prod_code",
        "site_code",
        "loc_code_from",
        "loc_code_to",
        "qty_puom",
        "p_uom",
        "qty_luom",
        "l_uom",
      ],
      PICKING_STOCK_DETAILS: [
        "prod_code",
        "site_code",
        "uppp",
        "p_uom",
        "l_uom",
        "pqty_stock",
        "lqty_stock",
        "pqty_picked",
        "lqty_picked",
        "pqty_avl",
        "lqty_avl",
      ],
    },
  },
};
