export interface IVW_AC_HEADER_SEARCH {
  company_code: string;
  doc_type: string;
  doc_no: number;
  doc_date: Date;
  ac_name: string;
  remarks: string;
  ref_no: string;
  create_user: string;
  cheque_no: string;
  cheque_date: Date;
  ac_payee: string;
  ref_doc_no: string;
  remittance: string;
  amount: number;
  canceled: string;
  div_code: string;
  fy_period: string;
  cheque_bank: string;
  user_id: string;
  create_dt: Date;
}
export interface IMS_AC_SETUP_DOC {
  curr_code: string;
  company_code: string;
  doc_id: string;
  doc_shortname: string;
  doc_name: string;
  doc_object: string;
  seq_no: string;
  default_h_ac: string;
  default_d_ac: string;
  default_sign: number;
  sign_editable: string;
  last_doc_no: number;
  prepared: string;
  verified: string;
  approved: string;
  received: string;
  back_date: number;
  prin_on_save: string;
  default_div_code: string;
  trans_type: string;
  doc_code: string;
  docno_prefix: string;
  default_h_code_co: string;
  updated_at?: Date;
  updated_by: string;
  created_by: string;
  created_at?: Date;
}
export interface IMS_AC_BANKCODE {
  company_code: string;
  ac_code: string;
  last_cheque_no: string;
  chq_template: string;
  words_length: number;
  bank_ac_code: string;
  bank_address: string;
  updated_at?: Date;
  updated_by: string;
  created_by: string;
  created_at?: Date;
}
export interface IMS_FY_PERIOD {
  company_code: string;
  fy_period: string;
  date_from: Date;
  date_to: Date;
  sort_order: number;
}
export interface ITransactionHeader {
  company_code: string;
  doc_type: string;
  doc_no: number;
  doc_date: Date;
  ac_code: string;
  bank_ac_code: string | null;
  ref_no: string | null;
  ref_date: Date | null;
  remarks: string | null;
  curr_code: string | null;
  ex_rate: number | null;
  cheque_no: string | null;
  cheque_date: Date | null;
  canceled: string | null;
  create_user: string;
  create_date: Date;
  last_serial_no: number;
  last_dtl_serial_no: number;
  payment_terms: string | null;
  lpo_no: string | null;
  lpo_date: Date | null;
  credit_period: number | null;
  due_date: Date | null;
  ref_doc_type: string | null;
  ac_payee: string | null;
  cheque_bank: string | null;
  party_name: string | null;
  party_address: string | null;
  party_phone: string | null;
  party_fax: string | null;
  remittance: string | null;
  auto_reverse: string | null;
  div_code: string | null;
  salesman_code: string | null;
  sector_code: string | null;
  sys_gen: string | null;
  tx_cat_code: string | null;
  tx_compntcat_code_1: string | null;
  tx_compntcat_code_2: string | null;
  tx_compntcat_code_3: string | null;
  tx_compntcat_code_4: string | null;
  tx_tax_filed: string | null;
  tx_tax_filed_dt: Date | null;
  tx_tax_filed_refno: string | null;
  tx_compnt_hdisc_amt_1: number | null;
  doc_path: string | null;
  ref_doc_no: string | null;
  vat_trn_no: string | null;
  updated_at?: Date;
  updated_by: string | null;
  created_by: string | null;
  created_at?: Date;
}

export interface IMsTaxCompntcategory {
  company_code: string;
  div_code: string;
  sr_no: number;
  tx_compnt_code: string;
  tx_cat_code: string;
  tx_subcat_code: string;
  tx_compntcat_code: string;
  tx_compntcat_name: string;
  tx_type: string;
  tx_percnt: number;
  tx_in_ac: string;
  tx_out_ac: string;
  tx_reverse_ac: string;
  tx_asset_ac: string;
  user_id: string;
  user_dt: Date;
}
export interface ITrAcInvdetail {
  c_bal_amt_org?: number;
  inv_amt?: number;
  IsDeletable?: boolean;
  company_code: string;
  doc_type: string;
  doc_no: number;
  serial_no: number;
  dtl_sr_no: number;
  doc_date: Date;
  ac_code: string;
  inv_no: string;
  inv_date: Date;
  due_date: Date;
  chq_no: string;
  chq_date: Date;
  chq_bank: string;
  amount: number;
  lcur_amount: number;
  sign_ind: number;
  curr_code: string;
  ex_rate: number;
  ex_rate_origin: number;
  curr_code_origin: string;
  amount_origin: number;
  indicator_origin: string;
  div_code: string;
  oracle_upload: string;
  oracle_dt: Date;
  created_by: string;
  created_at?: Date;
  updated_by: string;
  updated_at?: Date;
}
export interface IAcCodesSearch {
  company_code: string;
  ac_code: string;
  ac_name: string;
  curr_code: string;
  l4_bill: string;
  exp_type_code: string;
  l4_job: string;
  l4_description: string;
  l4_type: string;
  ac_status: string;
}
export interface IAcSetup {
  company_code: string;
  pdc_receipt_code: string;
  pdc_issue_code: string;
  doc_date_editable: string;
  ac_code: string;
  bank_name: string;
  ac_name: string;
  swift_code: string;
  base_curr_code: string;
  price_decimal_nos: number;
  amount_decimal_nos: number;
  lcur_decimal_nos: number;
  qty_decimal_nos: number;
  financial_yr_start: Date;
  financial_yr_end: Date;
  doc_edit_from: Date;
  doc_edit_to: Date;
  job_class: string;
  exchange_diff_ac: string;
  principal_ac_group: string;
  expsubtype_accident: string;
  expsubtype_fine: string;
  expsubtype_fuel: string;
  expsubtype_ins: string;
  expsubtype_reg: string;
  expsubtype_repair: string;
  expsubtype_service: string;
  supplier_ac_group: string;
  expcode_vehicle: string;
  age_1: number;
  age_2: number;
  age_3: number;
  age_4: number;
  age_5: number;
  docno_type: string;
  intercompany_ac_group: string;
  multy_div_accounting: string;
  bill_settle_lcur: string;
  default_tax_bstype: string;
  age_6: number;
  updated_at?: Date;
  updated_by: string;
  created_by: string;
  created_at?: Date;
  tax_perc: number;
}
export interface TTransactionDetail {
  company_code: string;
  doc_type: string;
  doc_no: number;
  serial_no: number;
  doc_date: Date;
  ac_code: string;
  header_ac_code: string | null;
  bank_ac_code: string | null;
  remarks: string | null;
  amount: number;
  sign_ind: number;
  curr_code: string | null;
  ex_rate: number | null;
  lcur_amount: number;
  pdc_ind: string | null;
  cheque_no: string | null;
  cheque_date: Date | null;
  cheque_desc: string | null;
  pdc_cleared_date: Date | null;
  cancelled: string | null;
  job_no: string | null;
  recon_ind: string | null;
  recon_date: Date | null;
  dept_code: string | null;
  qty: number | null;
  price: number | null;
  uom: string | null;
  pdc_clear_jvno: number | null;
  ref_doc_type: string | null;
  ref_doc_no: string | null;
  ref_doc_serial_no: number | null;
  div_code: string | null;
  tx_cat_code: string | null;
  tx_compntcat_code_1: string | null;
  tx_compntcat_code_2: string | null;
  tx_compntcat_code_3: string | null;
  tx_compntcat_code_4: string | null;
  tx_compnt_perc_1: number | null;
  tx_compnt_perc_2: number | null;
  tx_compnt_perc_3: number | null;
  tx_compnt_perc_4: number | null;
  tx_compnt_amt_1: number | null;
  tx_compnt_amt_2: number | null;
  tx_compnt_amt_3: number | null;
  tx_compnt_amt_4: number | null;
  tx_compnt_lcuramt_1: number | null;
  tx_compnt_lcuramt_2: number | null;
  tx_compnt_lcuramt_3: number | null;
  tx_compnt_lcuramt_4: number | null;
  tx_compnt_1_expmt: string | null;
  tx_compnt_2_expmt: string | null;
  tx_compnt_3_expmt: string | null;
  tx_compnt_4_expmt: string | null;
  tx_tax_filed: string | null;
  tx_tax_filed_dt: Date | null;
  tx_tax_filed_refno: string | null;
  tx_compnt_hdisc_amt_1: number | null;
  updated_at?: Date;
  updated_by: string | null;
  created_by: string | null;
  created_at?: Date;
}

export interface ITransactionJobDetail {
  company_code: string;
  doc_type: string;
  doc_no: number;
  serial_no: number;
  dtl_sr_no: number;
  doc_date: Date;
  ac_code: string;
  job_no: string;
  doc_refno: string;
  doc_refno_2: string;
  amount: number;
  sign_ind: number;
  lcur_amount: number;
  curr_code: string;
  ex_rate: number;
  div_code: string;
}
export interface ITransactionExpenseDetail {
  company_code: string;
  doc_type: string;
  doc_no: number;
  serial_no: number;
  dtl_sr_no: number;
  doc_date: Date;
  ac_code: string;
  exp_type_code: string;
  exp_subtype_code: string;
  exp_code: string;
  amount: number;
  sign_ind: number;
  lcur_amount: number;
  curr_code: string;
  ex_rate: number;
  div_code: string;
  job_no: string;
}
export interface IExpenseSubType {
  company_code: string;
  exp_subtype_code: string;
  exp_subtype_description: string;
  exp_type_code: string;
  dept_code: string;
  updated_at?: Date;
  updated_by: string;
  created_by: string;
  created_at?: Date;
}
export interface IExpenseType {
  exp_code: string;
  exp_description: string;
  exp_type_code: string;
  company_code: string;
  ref_code: string;
  updated_at?: Date;
  updated_by: string;
  created_by: string;
  created_at?: Date;
}
export interface IChequePaymentReport {
  doc_type: string;
  doc_no: Number;
  doc_date: Date;
  hdr_ac_code: string;
  hdr_remarks: string;
  hdr_curr_code: string;
  hdr_ex_rate: Number;
  cheque_no: string;
  cheque_date: Date;
  serial_no: Number;
  dtl_ac_code: string;
  remarks: string;
  amount: Number;
  sign_ind: Number;
  curr_code: string;
  ex_rate: Number;
  ac_name: string;
  ac_name_1: string;
  company_code: string;
  address_1: string;
  address_2: string;
  address_3: string;
  phone: string;
  fax: string;
  ref_no: string;
  ref_date: Date;
  ac_code: string;
  bank_name: string;
  company_address1: string;
  company_address2: string;
  company_address3: string;
  setup_ac_name: string;
  prepared: string;
  verified: string;
  approved: string;
  received: string;
  contact_person: string;
  payment_terms: string;
  qty: Number;
  price: Number;
  curr_sign: string;
  swift_code: string;
  lpo_no: string;
  lpo_date: Date;
  party_name: string;
  party_address: string;
  party_phone: string;
  party_fax: string;
  tx_compnt_amt_1: Number;
  ac_trn_no: string;
  tx_compnt_perc_1: Number;
  tx_compnt_lcuramt_1: Number;
  lcur_amount: Number;
  company_trn_no: string;
  company_name: string;
  bank_name_inv: string;
  ac_code_inv: string;
  reference_no_inv: string;
  bank_address_inv: string;
  swift_code_inv: string;
}
