export type TLeaveApproval = {
  SUPERVISOR: string;
  DIVISION_HEAD: string;
  REQUEST_NUMBER: string;
  REQUEST_DATE: string;
  EMPLOYEE_CODE: string;
  LEAVE_TYPE: string;
  LEAVE_START_DATE: string;
  LEAVE_END_DATE: string;
  RESUME_DATE?: string;
  LEAVE_DAYS?: number;
  REMARKS?: string;
  CREATED_BY: string;
  COMPANY_CODE: string;
  UPDATED_BY: string;
  LAST_ACTION?: string;
  alternate_id?: string;
  HOD?: string;
  IMMEDIATE_SUPERVISOR?: string;
  DEPT_HEAD?: string;
  LEAVE_ALLOWANCE?: number;
  ADV_PAYMENT?: number;
  CAUSE_TYPE?: string;
  TRAVEL_DATE?: string;
  NAME_OF_REPLACEMENT?: string;
  CONTACT_DETAILS_DURING_LEAVE?: string;
};