import { DataTypes, Model } from "sequelize";
import { sequelize } from "../../database/connection";
import constants from "../../helpers/constants";
import { IProductEdi } from "../../interfaces/wms/gm_wms.interface";

class ProductEdi extends Model<IProductEdi> {}

ProductEdi.init(
  {
    PRIN_CODE: {
      type: DataTypes.STRING(7),
      allowNull: false,
      field: "PRIN_CODE",
    },
    PROD_CODE: {
      type: DataTypes.STRING(40),
      allowNull: false,
      primaryKey: true,
      field: "PROD_CODE",
    },
    COMPANY_CODE: {
      type: DataTypes.STRING(7),
      allowNull: false,
      primaryKey: true,
      field: "COMPANY_CODE",
    },
    PROD_NAME: {
      type: DataTypes.STRING(250),
      allowNull: false,
      field: "PROD_NAME",
    },
    GROUP_CODE: { type: DataTypes.STRING(5), field: "GROUP_CODE" },
    BRAND_CODE: { type: DataTypes.STRING(5), field: "BRAND_CODE" },
    PACKDESC: { type: DataTypes.STRING(50), field: "PACKDESC" },
    BARCODE: { type: DataTypes.STRING(40), field: "BARCODE" },
    P_UOM: { type: DataTypes.STRING(5), field: "P_UOM" },
    SUOM: { type: DataTypes.STRING(5), field: "SUOM" },
    LENGTH: { type: DataTypes.DECIMAL(12, 6), field: "LENGTH" },
    BREADTH: { type: DataTypes.DECIMAL(12, 6), field: "BREADTH" },
    HEIGHT: { type: DataTypes.DECIMAL(12, 6), field: "HEIGHT" },
    VOLUME: { type: DataTypes.DECIMAL(12, 6), field: "VOLUME" },
    GROSS_WT: { type: DataTypes.DECIMAL(12, 6), field: "GROSS_WT" },
    NET_WT: { type: DataTypes.DECIMAL(12, 6), field: "NET_WT" },
    FOC: { type: DataTypes.STRING(20), field: "FOC" },
    CPU: { type: DataTypes.DECIMAL(10, 4), field: "CPU" },
    HARM_CODE: { type: DataTypes.STRING(20), field: "HARM_CODE" },
    IMCO_CODE: { type: DataTypes.STRING(20), field: "IMCO_CODE" },
    KITTING: { type: DataTypes.STRING(1), field: "KITTING" },
    MANU_CODE: { type: DataTypes.STRING(25), field: "MANU_CODE" },
    BASE_PRICE: { type: DataTypes.DECIMAL(16, 6), field: "BASE_PRICE" },
    FLAT_STORAGE: { type: DataTypes.DECIMAL(10, 4), field: "FLAT_STORAGE" },
    SITE_TYPE: { type: DataTypes.STRING(5), field: "SITE_TYPE" },
    SITE_IND: { type: DataTypes.STRING(5), field: "SITE_IND" },
    PACK_KEY: { type: DataTypes.STRING(40), field: "PACK_KEY" },
    PROD_TI: { type: DataTypes.INTEGER, field: "PROD_TI" },
    PROD_HI: { type: DataTypes.INTEGER, field: "PROD_HI" },
    CHARGETIME: { type: DataTypes.STRING(5), field: "CHARGETIME" },
    PROD_STATUS: { type: DataTypes.STRING(2), field: "PROD_STATUS" },
    SHELF_LIFE: { type: DataTypes.INTEGER, field: "SHELF_LIFE" },
    CATEGORY_ABC: { type: DataTypes.STRING(2), field: "CATEGORY_ABC" },
    REORD_LEVEL: { type: DataTypes.INTEGER, field: "REORD_LEVEL" },
    REORD_QTY: { type: DataTypes.DECIMAL(12, 1), field: "REORD_QTY" },
    ALT_PROD_CODE: { type: DataTypes.STRING(40), field: "ALT_PROD_CODE" },
    PREF_SITE: { type: DataTypes.STRING(5), field: "PREF_SITE" },
    PREF_LOC_FROM: { type: DataTypes.STRING(15), field: "PREF_LOC_FROM" },
    PREF_LOC_TO: { type: DataTypes.STRING(15), field: "PREF_LOC_TO" },
    PREF_AISLE_FROM: { type: DataTypes.STRING(5), field: "PREF_AISLE_FROM" },
    PREF_AISLE_TO: { type: DataTypes.STRING(5), field: "PREF_AISLE_TO" },
    PREF_COL_FROM: { type: DataTypes.INTEGER, field: "PREF_COL_FROM" },
    PREF_COL_TO: { type: DataTypes.INTEGER, field: "PREF_COL_TO" },
    PREF_HT_FROM: { type: DataTypes.INTEGER, field: "PREF_HT_FROM" },
    PREF_HT_TO: { type: DataTypes.INTEGER, field: "PREF_HT_TO" },
    UPPP: { type: DataTypes.INTEGER, field: "UPPP" },
    CHK_MANUCODE: { type: DataTypes.STRING(1), field: "CHK_MANUCODE" },
    CHK_LOTNO: { type: DataTypes.STRING(1), field: "CHK_LOTNO" },
    CHK_MFGEXPDT: { type: DataTypes.STRING(1), field: "CHK_MFGEXPDT" },
    PUOM_VOLUME: { type: DataTypes.DECIMAL(12, 6), field: "PUOM_VOLUME" },
    PUOM_NETWT: { type: DataTypes.DECIMAL(12, 6), field: "PUOM_NETWT" },
    PUOM_GROSSWT: { type: DataTypes.DECIMAL(12, 6), field: "PUOM_GROSSWT" },
    L_UOM: { type: DataTypes.STRING(5), field: "L_UOM" },
    LUPPP: { type: DataTypes.INTEGER, field: "LUPPP" },
    UOM_COUNT: { type: DataTypes.INTEGER, field: "UOM_COUNT" },
    PROD_TYPE: { type: DataTypes.INTEGER, field: "PROD_TYPE" },
    TWOPLUS_UOM: { type: DataTypes.STRING(1), field: "TWOPLUS_UOM" },
    UPP: { type: DataTypes.INTEGER, field: "UPP" },
    WAVE_CODE: { type: DataTypes.INTEGER, field: "WAVE_CODE" },
    PRODUCT_STAGE: { type: DataTypes.STRING(1), field: "PRODUCT_STAGE" },
    CO_PACK: { type: DataTypes.STRING(1), field: "CO_PACK" },
    MODEL_NUMBER: { type: DataTypes.STRING(50), field: "MODEL_NUMBER" },
    VARIANT_CODE: { type: DataTypes.STRING(4), field: "VARIANT_CODE" },
    CNT_ORIGIN: { type: DataTypes.STRING(20), field: "CNT_ORIGIN" },
    SERIALIZE: { type: DataTypes.STRING(1), field: "SERIALIZE" },
    PACKING: { type: DataTypes.STRING(20), field: "PACKING" },
    OLD_UPP: { type: DataTypes.DECIMAL(38, 0), field: "OLD_UPP" },
    AVG_CONSUMPTION: {
      type: DataTypes.DECIMAL(38, 0),
      field: "AVG_CONSUMPTION",
    },
    PROD_IMAGE_PATH_WEB: {
      type: DataTypes.STRING(250),
      field: "PROD_IMAGE_PATH_WEB",
    },
    MINPERIOD_EXPPICK: { type: DataTypes.INTEGER, field: "MINPERIOD_EXPPICK" },
    RCPT_EXP_LIMIT: { type: DataTypes.INTEGER, field: "RCPT_EXP_LIMIT" },
    QTY_AS_WT: { type: DataTypes.STRING(1), field: "QTY_AS_WT" },
    HAZMAT_IND: { type: DataTypes.STRING(1), field: "HAZMAT_IND" },
    HAZMAT_CLASS: { type: DataTypes.STRING(10), field: "HAZMAT_CLASS" },
    FOOD_IND: { type: DataTypes.STRING(1), field: "FOOD_IND" },
    PHARMA_IND: { type: DataTypes.STRING(1), field: "PHARMA_IND" },
    SPECIAL_INSTRUCTIONS: {
      type: DataTypes.STRING(100),
      field: "SPECIAL_INSTRUCTIONS",
    },
    STRENGTH: { type: DataTypes.STRING(50), field: "STRENGTH" },
    PACK_SIZE: { type: DataTypes.DECIMAL(10, 0), field: "PACK_SIZE" },
    GROUP_CODE_BK: { type: DataTypes.STRING(10), field: "GROUP_CODE_BK" },
    BATCH_TYPE: { type: DataTypes.INTEGER, field: "BATCH_TYPE" },
    SAP_PROD_CODE: { type: DataTypes.STRING(20), field: "SAP_PROD_CODE" },
    SAP_PROD_DESC: { type: DataTypes.STRING(250), field: "SAP_PROD_DESC" },
    TEMP_CODE: { type: DataTypes.STRING(250), field: "TEMP_CODE" },
    EDIT_USER: { type: DataTypes.STRING(10), field: "EDIT_USER" },
    CLASS: { type: DataTypes.STRING(1), field: "CLASS" },
    WOB: { type: DataTypes.DECIMAL(10, 0), field: "WOB" },
    UNIFIED_CODE: { type: DataTypes.STRING(20), field: "UNIFIED_CODE" },
    CURRENT_SEASON: { type: DataTypes.STRING(50), field: "CURRENT_SEASON" },
    PRODUCT_CATEGORY: { type: DataTypes.STRING(50), field: "PRODUCT_CATEGORY" },
    GENERIC_ARTICLE: { type: DataTypes.STRING(50), field: "GENERIC_ARTICLE" },
    PROD_GENDER: { type: DataTypes.STRING(50), field: "PROD_GENDER" },
    PROD_COLOR: { type: DataTypes.STRING(50), field: "PROD_COLOR" },
    PROD_SIZE: { type: DataTypes.STRING(50), field: "PROD_SIZE" },
    PRNT_P_CODE: { type: DataTypes.STRING(50), field: "PRNT_P_CODE" },
    UPDATED_AT: {
      type: DataTypes.DATE,
      field: "UPDATED_AT",
      defaultValue: DataTypes.NOW,
    },
    UPDATED_BY: { type: DataTypes.STRING(50), field: "UPDATED_BY" },
    CREATED_BY: { type: DataTypes.STRING(20), field: "CREATED_BY" },
    CREATED_AT: {
      type: DataTypes.DATE,
      field: "CREATED_AT",
      defaultValue: DataTypes.NOW,
    },
    DIV_CODE: { type: DataTypes.STRING(20), field: "DIV_CODE" },
    AWS_PATH: { type: DataTypes.STRING(255), field: "AWS_PATH" },
  },
  {
    sequelize,
    modelName: "Product",
    tableName: constants.TABLE.MS_PRODUCT1,
    timestamps: false,
    indexes: [
      {
        unique: true,
        fields: ["PROD_CODE"],
      },
    ],
  }
);

export default ProductEdi;
