export type TDivision = {
  div_code: string;
  div_name: string;
  company_code?: string;
  div_short_name?: string;
  div_address1?: string;
  div_address2?: string;
  div_address3?: string;
  country_code?: string;
  phone?: string;
  fax?: string;
  email?: string;
  //  div_head_id?:string;
  //  reamrks?:string;
  //  status?:string;
  //  user_id?:string;
  //  user_dt?:Date;
  //  enterprice_code?:string;
  //  payroll_date?:Date;
  //  payroll_status?:string;
  //  normal_working_hrs?:number;
  //  //day_off1?:string;
  //day_off2?:string;
  //hr_representative?:string;
  //pay_month?:number;
  //pay_year?:number;
  //payroll_calc_type?:string;
  //day_off1_half_day?:string;
  //day_off2_half_day?:string;
  //fin_year_start?:Date;
  //fin_year_end?:Date;
  //back_name_inv?:string;
  //ac_code_inv?:string;
  //reference_no_inv?:string;
  //bank_address_inv?:string;
  //swift_code_inv?:string;
  //emp_document_path?:string;
  //payroll_cutoff_date?:Date;
  //payroll_day?:number;
  //emp_acgroup?:string;
  //emp_cnt?:string;
  //trn_no?:string
  //comp_logo?:string;
  //logo_title?:string;
  //default_grade?:string;
  //employer_eid?:string;
  //payer_eid?:string;
  //payer_qid?:string;
  //payer_bank?:string;
  // payer_iban?:string;
  created_at?: Date;
  created_by?: string;
  updated_at?: Date;
  updated_by?: string;
};
