export type TTsStnDetailEdi = {
  company_code: string;
  stn_no: number;
  prin_code: string;
  prod_code?: string;
  prod_name?: string;
  site_code?: string;
  job_no?: string;
  pallet_id?: string;
  lot_no_from?: string;
  lot_no_to?: string;
  batch_no_from?: string;
  batch_no_to?: string;
  p_uom?: string;
  l_uom?: string;
  from_site?: string;
  to_site?: string;
  from_loc_start?: string;
  from_loc_end?: string;
  to_loc_start?: string;
  to_loc_end?: string;
  key_number?: string;
  quantity?: number;
  qty_puom?: number;
  qty_luom?: number;
  mfg_date_from?: string | null;
  mfg_date_to?: string | null;
  exp_date_from?: string | null;
  exp_date_to?: string | null;
  user_id?: string;
};